Repository milvus-io/bootcamp, pull requests merged in 2021-08, with the labels that each got.

#581 Update README
  README.md
Labels: size/XS

#588 Update README.md
  README.md
Labels: size/XS

#594 clean output
  etc/onnx_and_milvus/milvus_with_different_models.ipynb
Labels: size/L

#595 del link about zilliz-demo
  README.md
Labels: size/XS

#598 Video Similarity Search: Upload Object Detection
  solutions/video_similarity_search/object_detection/README.md
  solutions/video_similarity_search/object_detection/server/Dockerfile
  solutions/video_similarity_search/object_detection/server/requirements.txt
  solutions/video_similarity_search/object_detection/server/src/__init__.py
  solutions/video_similarity_search/object_detection/server/src/config.py
  solutions/video_similarity_search/object_detection/server/src/encode.py
  solutions/video_similarity_search/object_detection/server/src/frame_extract.py
  solutions/video_similarity_search/object_detection/server/src/logs.py
  solutions/video_similarity_search/object_detection/server/src/main.py
  solutions/video_similarity_search/object_detection/server/src/milvus_helpers.py
  solutions/video_similarity_search/object_detection/server/src/mysql_helpers.py
  solutions/video_similarity_search/object_detection/server/src/operations/count.py
  solutions/video_similarity_search/object_detection/server/src/operations/drop.py
  solutions/video_similarity_search/object_detection/server/src/operations/load.py
  solutions/video_similarity_search/object_detection/server/src/operations/search.py
  solutions/video_similarity_search/object_detection/server/src/yolov3_detector/__init__.py
  solutions/video_similarity_search/object_detection/server/src/yolov3_detector/data/prepare_model.sh
  solutions/video_similarity_search/object_detection/server/src/yolov3_detector/paddle_yolo.py
  solutions/video_similarity_search/object_detection/server/src/yolov3_detector/yolo_infer.py
Labels: size/XXL

#601 remove warnings
  solutions/text_search_engine/quick_deploy/client/src/App.tsx
  solutions/text_search_engine/quick_deploy/client/src/components/common/SnackBar.tsx
  solutions/text_search_engine/quick_deploy/client/src/components/pages/SearchPage/SearchBar.tsx
  solutions/text_search_engine/quick_deploy/client/src/components/pages/SearchPage/SearchPage.tsx
Labels: size/S

#602 add gitattributes
  .gitattributes
Labels: size/M

#609 update README
  README.md
Labels: size/M

#610 Update README.md
  solutions/audio_similarity_search/quick_deploy/README.md
Labels: size/XS
