Repository milvus-io/bootcamp, pull requests merged in 2021-07, with the labels that each got.

#550 add audio search demo
  solutions/audio_similarity_search/quick_deploy/client/.gitignore
  solutions/audio_similarity_search/quick_deploy/client/README.md
  solutions/audio_similarity_search/quick_deploy/client/env.config.js
  solutions/audio_similarity_search/quick_deploy/client/package.json
  solutions/audio_similarity_search/quick_deploy/client/public/favicon.ico
  solutions/audio_similarity_search/quick_deploy/client/public/index.html
  solutions/audio_similarity_search/quick_deploy/client/public/logo192.png
  solutions/audio_similarity_search/quick_deploy/client/public/logo512.png
  solutions/audio_similarity_search/quick_deploy/client/public/manifest.json
  solutions/audio_similarity_search/quick_deploy/client/public/robots.txt
  solutions/audio_similarity_search/quick_deploy/client/src/App.css
  solutions/audio_similarity_search/quick_deploy/client/src/App.test.tsx
  solutions/audio_similarity_search/quick_deploy/client/src/App.tsx
  solutions/audio_similarity_search/quick_deploy/client/src/components/audioPlayer.tsx
  solutions/audio_similarity_search/quick_deploy/client/src/components/header.tsx
  solutions/audio_similarity_search/quick_deploy/client/src/components/search.tsx
  solutions/audio_similarity_search/quick_deploy/client/src/components/searchResults.tsx
  solutions/audio_similarity_search/quick_deploy/client/src/components/sidebar.tsx
  solutions/audio_similarity_search/quick_deploy/client/src/components/uploader.tsx
  solutions/audio_similarity_search/quick_deploy/client/src/context/index.tsx
  solutions/audio_similarity_search/quick_deploy/client/src/index.css
  solutions/audio_similarity_search/quick_deploy/client/src/index.tsx
  solutions/audio_similarity_search/quick_deploy/client/src/logo.svg
  solutions/audio_similarity_search/quick_deploy/client/src/pages/home.tsx
  solutions/audio_similarity_search/quick_deploy/client/src/react-app-env.d.ts
  solutions/audio_similarity_search/quick_deploy/client/src/reportWebVitals.ts
  solutions/audio_similarity_search/quick_deploy/client/src/setupTests.ts
  solutions/audio_similarity_search/quick_deploy/client/src/utils/axios.js
  solutions/audio_similarity_search/quick_deploy/client/src/utils/common.ts
  solutions/audio_similarity_search/quick_deploy/client/src/utils/http.ts
  solutions/audio_similarity_search/quick_deploy/client/tsconfig.json
  solutions/audio_similarity_search/quick_deploy/client/yarn.lock
Labels: size/XXL

#551 add docker file to audio-demo
  solutions/audio_similarity_search/quick_deploy/client/.env
  solutions/audio_similarity_search/quick_deploy/client/Dockerfile
  solutions/audio_similarity_search/quick_deploy/client/conf/conf.d/client.conf
  solutions/audio_similarity_search/quick_deploy/client/conf/conf.d/gzip.conf
  solutions/audio_similarity_search/quick_deploy/client/env.sh
Labels: size/L

#554 update README
  README.md
  images/logo.png
  images/screenshot.png
Labels: size/L

#557 Readme update
  README.md
Labels: size/S

#558 Update audio server requirements, change listening address
  solutions/audio_similarity_search/quick_deploy/server/main.py
  solutions/audio_similarity_search/quick_deploy/server/requirements.txt
Labels: size/XS

#561 Updated audio search readme and config file
  solutions/audio_similarity_search/quick_deploy/README.md
  solutions/audio_similarity_search/quick_deploy/pic/insertgui.png
  solutions/audio_similarity_search/quick_deploy/pic/searchgui.png
  solutions/audio_similarity_search/quick_deploy/server/src/config.py
  solutions/audio_similarity_search/quick_deploy/server/src/milvus_helpers.py
Labels: size/M

#564 Audio Search Readme- new API docs and pics
  solutions/audio_similarity_search/quick_deploy/README.md
  solutions/audio_similarity_search/quick_deploy/pic/all_API.png
  solutions/audio_similarity_search/quick_deploy/pic/allapi.png
  solutions/audio_similarity_search/quick_deploy/pic/insert.png
  solutions/audio_similarity_search/quick_deploy/pic/search.png
Labels: size/M

#562 updating readme with api
  solutions/molecular_similarity_search/quick_deploy/README.md
  solutions/molecular_similarity_search/quick_deploy/pic/api.PNG
Labels: size/M
