Repository milvus-io/bootcamp, pull requests merged in 2021-12, with the labels that each got.

#983 Making README more readable.
  solutions/text_search_engine/quick_deploy/README.md
Labels: size/M

#984 Fix typo
  solutions/reverse_image_search/quick_deploy/README.md
Labels: size/XS

#989 Change config to use full data
  solutions/milvus3d/jupyter_notebook/notebook_config.py
Labels: size/XS

#988 Update milvus3d notebook
  solutions/milvus3d/jupyter_notebook/milvus3d_demo.ipynb
  solutions/milvus3d/jupyter_notebook/notebook_config.py
Labels: jupyter, size/L

#990 Fix bugs
  solutions/milvus3d/jupyter_notebook/milvus3d_demo.ipynb
Labels: jupyter
