Repository milvus-io/bootcamp, pull requests merged in 2021-11, with the labels that each got.

#857 Fix config.py in movive recommender
  solutions/recommender_system/quick_deploy/movie_recommender/milvus_tool/config.py
Labels: size/XS

#843 Update code of mol_search
  solutions/molecular_similarity_search/quick_deploy/README.md
  solutions/molecular_similarity_search/quick_deploy/server/Dockerfile
  solutions/molecular_similarity_search/quick_deploy/server/main.py
  solutions/molecular_similarity_search/quick_deploy/server/src/config.py
  solutions/molecular_similarity_search/quick_deploy/server/src/encode.py
  solutions/molecular_similarity_search/quick_deploy/server/src/helpers/milvus_helpers.py
  solutions/molecular_similarity_search/quick_deploy/server/src/helpers/mysql_helpers.py
  solutions/molecular_similarity_search/quick_deploy/server/src/logs.py
  solutions/molecular_similarity_search/quick_deploy/server/src/operations/__init__.py
  solutions/molecular_similarity_search/quick_deploy/server/src/operations/count.py
  solutions/molecular_similarity_search/quick_deploy/server/src/operations/drop.py
  solutions/molecular_similarity_search/quick_deploy/server/src/operations/load.py
  solutions/molecular_similarity_search/quick_deploy/server/src/operations/search.py
Labels: size/L

#834 Update video_quick_deploy code with pylint check
  solutions/video_similarity_search/quick_deploy/README.md
  solutions/video_similarity_search/quick_deploy/server/Dockerfile
  solutions/video_similarity_search/quick_deploy/server/src/config.py
  solutions/video_similarity_search/quick_deploy/server/src/encode.py
  solutions/video_similarity_search/quick_deploy/server/src/frame_extract.py
  solutions/video_similarity_search/quick_deploy/server/src/logs.py
  solutions/video_similarity_search/quick_deploy/server/src/main.py
  solutions/video_similarity_search/quick_deploy/server/src/milvus_helpers.py
  solutions/video_similarity_search/quick_deploy/server/src/mysql_helpers.py
  solutions/video_similarity_search/quick_deploy/server/src/operations/count.py
  solutions/video_similarity_search/quick_deploy/server/src/operations/drop.py
  solutions/video_similarity_search/quick_deploy/server/src/operations/load.py
  solutions/video_similarity_search/quick_deploy/server/src/operations/search.py
Labels: size/L

#836 Update code in video_object_detection
  solutions/video_similarity_search/object_detection/server/Dockerfile
  solutions/video_similarity_search/object_detection/server/src/config.py
  solutions/video_similarity_search/object_detection/server/src/encode.py
  solutions/video_similarity_search/object_detection/server/src/frame_extract.py
  solutions/video_similarity_search/object_detection/server/src/logs.py
  solutions/video_similarity_search/object_detection/server/src/main.py
  solutions/video_similarity_search/object_detection/server/src/milvus_helpers.py
  solutions/video_similarity_search/object_detection/server/src/mysql_helpers.py
  solutions/video_similarity_search/object_detection/server/src/operations/count.py
  solutions/video_similarity_search/object_detection/server/src/operations/drop.py
  solutions/video_similarity_search/object_detection/server/src/operations/load.py
  solutions/video_similarity_search/object_detection/server/src/operations/search.py
  solutions/video_similarity_search/object_detection/server/src/yolov3_detector/__init__.py
  solutions/video_similarity_search/object_detection/server/src/yolov3_detector/paddle_yolo.py
  solutions/video_similarity_search/object_detection/server/src/yolov3_detector/yolo_infer.py
Labels: size/L

#837 Update code of img_quick_deploy
  solutions/reverse_image_search/quick_deploy/README.md
  solutions/reverse_image_search/quick_deploy/server/Dockerfile
  solutions/reverse_image_search/quick_deploy/server/src/config.py
  solutions/reverse_image_search/quick_deploy/server/src/encode.py
  solutions/reverse_image_search/quick_deploy/server/src/logs.py
  solutions/reverse_image_search/quick_deploy/server/src/main.py
  solutions/reverse_image_search/quick_deploy/server/src/milvus_helpers.py
  solutions/reverse_image_search/quick_deploy/server/src/mysql_helpers.py
  solutions/reverse_image_search/quick_deploy/server/src/operations/count.py
  solutions/reverse_image_search/quick_deploy/server/src/operations/drop.py
  solutions/reverse_image_search/quick_deploy/server/src/operations/load.py
  solutions/reverse_image_search/quick_deploy/server/src/operations/search.py
  solutions/reverse_image_search/quick_deploy/server/src/operations/upload.py
Labels: size/L

#839 Update code of img_object_detection
  solutions/reverse_image_search/object_detection/README.md
  solutions/reverse_image_search/object_detection/server/src/config.py
  solutions/reverse_image_search/object_detection/server/src/encode.py
  solutions/reverse_image_search/object_detection/server/src/logs.py
  solutions/reverse_image_search/object_detection/server/src/main.py
  solutions/reverse_image_search/object_detection/server/src/milvus_helpers.py
  solutions/reverse_image_search/object_detection/server/src/mysql_helpers.py
  solutions/reverse_image_search/object_detection/server/src/operations/count.py
  solutions/reverse_image_search/object_detection/server/src/operations/drop.py
  solutions/reverse_image_search/object_detection/server/src/operations/load.py
  solutions/reverse_image_search/object_detection/server/src/operations/search.py
Labels: size/L

#840 Update code of audio_search
  solutions/audio_similarity_search/quick_deploy/server/Dockerfile
  solutions/audio_similarity_search/quick_deploy/server/main.py
  solutions/audio_similarity_search/quick_deploy/server/src/config.py
  solutions/audio_similarity_search/quick_deploy/server/src/encode.py
  solutions/audio_similarity_search/quick_deploy/server/src/logs.py
  solutions/audio_similarity_search/quick_deploy/server/src/milvus_helpers.py
  solutions/audio_similarity_search/quick_deploy/server/src/mysql_helpers.py
  solutions/audio_similarity_search/quick_deploy/server/src/operations/__init__.py
  solutions/audio_similarity_search/quick_deploy/server/src/operations/count.py
  solutions/audio_similarity_search/quick_deploy/server/src/operations/drop.py
  solutions/audio_similarity_search/quick_deploy/server/src/operations/load.py
  solutions/audio_similarity_search/quick_deploy/server/src/operations/search.py
Labels: size/L

#860 Update config.py to pass pylint
  solutions/recommender_system/quick_deploy/movie_recommender/milvus_tool/config.py
Labels: size/XS

#835 update text search engine code with pylint check
  solutions/text_search_engine/quick_deploy/server/src/config.py
  solutions/text_search_engine/quick_deploy/server/src/logs.py
  solutions/text_search_engine/quick_deploy/server/src/main.py
  solutions/text_search_engine/quick_deploy/server/src/milvus_helpers.py
  solutions/text_search_engine/quick_deploy/server/src/mysql_helpers.py
  solutions/text_search_engine/quick_deploy/server/src/operations/count.py
  solutions/text_search_engine/quick_deploy/server/src/operations/drop.py
  solutions/text_search_engine/quick_deploy/server/src/operations/load.py
  solutions/text_search_engine/quick_deploy/server/src/operations/search.py
Labels: size/L

#838 update qa quick_deploy code with pylint check
  solutions/question_answering_system/quick_deploy/server/src/config.py
  solutions/question_answering_system/quick_deploy/server/src/encode.py
  solutions/question_answering_system/quick_deploy/server/src/logs.py
  solutions/question_answering_system/quick_deploy/server/src/main.py
  solutions/question_answering_system/quick_deploy/server/src/milvus_helpers.py
  solutions/question_answering_system/quick_deploy/server/src/mysql_helpers.py
  solutions/question_answering_system/quick_deploy/server/src/operations/count.py
  solutions/question_answering_system/quick_deploy/server/src/operations/drop.py
  solutions/question_answering_system/quick_deploy/server/src/operations/load.py
  solutions/question_answering_system/quick_deploy/server/src/operations/search.py
Labels: size/L

#845 Update benchmark scripts code with pylint check
  benchmark_test/scripts/config.py
  benchmark_test/scripts/load.py
  benchmark_test/scripts/logs.py
  benchmark_test/scripts/main.py
  benchmark_test/scripts/milvus_helpers.py
  benchmark_test/scripts/performance_test.py
  benchmark_test/scripts/recall_test.py
Labels: size/L

#842 Update dna quick_deploy code with pylint check
  solutions/dna_sequence_classification/quick_deploy/server/src/config.py
  solutions/dna_sequence_classification/quick_deploy/server/src/logs.py
  solutions/dna_sequence_classification/quick_deploy/server/src/main.py
  solutions/dna_sequence_classification/quick_deploy/server/src/milvus_helpers.py
  solutions/dna_sequence_classification/quick_deploy/server/src/mysql_helpers.py
  solutions/dna_sequence_classification/quick_deploy/server/src/operations/count.py
  solutions/dna_sequence_classification/quick_deploy/server/src/operations/drop.py
  solutions/dna_sequence_classification/quick_deploy/server/src/operations/load.py
  solutions/dna_sequence_classification/quick_deploy/server/src/operations/search.py
  solutions/dna_sequence_classification/quick_deploy/server/src/utils.py
Labels: size/L

#858 Enhancement Jupyter Notebook tutorial for image hash search
  solutions/reverse_image_search/image_hash/.gitignore
  solutions/reverse_image_search/image_hash/image_hash_search.ipynb
  solutions/reverse_image_search/image_hash/requirements.txt
Labels: size/XXL

#870 Update um.py to pass pylint
  solutions/recommender_system/quick_deploy/movie_recommender/um.py
Labels: size/S

#869 Update to_redis.py to pass pylint
  solutions/recommender_system/quick_deploy/movie_recommender/to_redis.py
Labels: size/S

#868 Update to_milvus.py to pass pylint
  solutions/recommender_system/quick_deploy/movie_recommender/to_milvus.py
Labels: size/S

#867 Update test_client.py to pass pylint
  solutions/recommender_system/quick_deploy/movie_recommender/test_client.py
Labels: size/S

#866 Update recall.py to pass pylint
  solutions/recommender_system/quick_deploy/movie_recommender/recall.py
Labels: size/S

#865 Update rank.py to pass pylint
  solutions/recommender_system/quick_deploy/movie_recommender/rank.py
Labels: size/S

#864 Update cm.py to pass pylint
  solutions/recommender_system/quick_deploy/movie_recommender/cm.py
Labels: size/S

#863 Update as.py to pass pylint
  solutions/recommender_system/quick_deploy/movie_recommender/as.py
Labels: size/M

#862 Update milvus_recall to pass pylint
  solutions/recommender_system/quick_deploy/movie_recommender/milvus_tool/milvus_recall.py
Labels: size/S

#861 Update milvus_insert to pass pylint
  solutions/recommender_system/quick_deploy/movie_recommender/milvus_tool/milvus_insert.py
Labels: size/M

#871 Update requirements.txt with adaptive versions
  solutions/recommender_system/requirements.txt
Labels: size/XS

#872 Add test_main for audio search
  solutions/audio_similarity_search/quick_deploy/server/src/logs.py
  solutions/audio_similarity_search/quick_deploy/server/src/main.py
  solutions/audio_similarity_search/quick_deploy/server/src/milvus_helpers.py
  solutions/audio_similarity_search/quick_deploy/server/src/operations/count.py
  solutions/audio_similarity_search/quick_deploy/server/src/operations/drop.py
  solutions/audio_similarity_search/quick_deploy/server/src/operations/load.py
  solutions/audio_similarity_search/quick_deploy/server/src/operations/search.py
  solutions/audio_similarity_search/quick_deploy/server/src/test_main.py
Labels: size/L

#874 Add jupyter-ci
  .github/workflows/jupyter_ci.yml
Labels: size/M

#873 Add Deploy-CI-Test
  .github/workflows/deploy_ci.yml
  .github/workflows/pylint.yml
  solutions/audio_similarity_search/quick_deploy/server/requirements.txt
Labels: size/M

#877 modify QA/encode.py
  solutions/question_answering_system/quick_deploy/server/src/encode.py
Labels: size/S

#876 Update audio.jupyter
  solutions/audio_similarity_search/audio_similarity_search.ipynb
  solutions/audio_similarity_search/requirements.txt
Labels: size/S, jupyter

#875 Delete png of hacktoberfest
  README.md
Labels: documentation, size/XS

#878 Add test code for QA
  solutions/question_answering_system/quick_deploy/server/requirements.txt
  solutions/question_answering_system/quick_deploy/server/src/encode.py
  solutions/question_answering_system/quick_deploy/server/src/test_main.py
Labels: size/M, question_answering_system/quick_deploy

#879 Delete labeled
  .github/workflows/deploy_ci.yml
Labels: size/XS

#881 Modify the requirements.txt for QA
  solutions/question_answering_system/quick_deploy/server/requirements.txt
Labels: size/XS

#883 Fix dna: milvus_helper
  solutions/dna_sequence_classification/quick_deploy/server/src/milvus_helpers.py
Labels: size/XS

#882 Fix dna: mysql_helpers
  solutions/dna_sequence_classification/quick_deploy/server/src/mysql_helpers.py
Labels: size/XS

#885 Update deploy_ci.yml
  .github/workflows/deploy_ci.yml
Labels: size/XS

#888 Update pytest ci
  .github/workflows/deploy_ci.yml
Labels: size/XS

#887 Add test script for dna
  solutions/dna_sequence_classification/quick_deploy/server/requirements.txt
  solutions/dna_sequence_classification/quick_deploy/server/src/test_main.py
  solutions/dna_sequence_classification/requirements.txt
Labels: size/M, dna_sequence_classification/quick_deploy

#886 update video search test script
  solutions/video_similarity_search/quick_deploy/server/requirements.txt
  solutions/video_similarity_search/quick_deploy/server/src/operations/drop.py
  solutions/video_similarity_search/quick_deploy/server/src/test_main.py
Labels: size/M, video_similarity_search/quick_deploy

#889 Add test script for reverse_image_search
  solutions/reverse_image_search/quick_deploy/server/src/config.py
  solutions/reverse_image_search/quick_deploy/server/src/test_main.py
Labels: reverse_image_search/quick_deploy

#891 modify config.py for Benchmark
  benchmark_test/scripts/config.py
  benchmark_test/scripts/test_main.py
Labels: size/M

#892 modify main.py for benchmark
  benchmark_test/scripts/main.py
Labels: size/XS

#893 modify milvus_helpers.py for benchmark
  benchmark_test/scripts/milvus_helpers.py
Labels: size/M

#894 modify recall_test.py for benchmark
  benchmark_test/scripts/recall_test.py
Labels: size/XS

#895 Test
  .github/workflows/deploy_ci.yml
Labels: size/S

#896 modify requirements.txt of benchmark
  benchmark_test/scripts/requirements.txt
Labels: size/XS

#890 update text search test script
  solutions/text_search_engine/quick_deploy/server/requirements.txt
  solutions/text_search_engine/quick_deploy/server/src/config.py
  solutions/text_search_engine/quick_deploy/server/src/data/example.csv
  solutions/text_search_engine/quick_deploy/server/src/encode.py
  solutions/text_search_engine/quick_deploy/server/src/main.py
  solutions/text_search_engine/quick_deploy/server/src/operations/load.py
  solutions/text_search_engine/quick_deploy/server/src/operations/search.py
  solutions/text_search_engine/quick_deploy/server/src/test_main.py
Labels: size/L, text_search_engine/quick_deploy

#897 Add test script for benchmark
  benchmark_test/scripts/requirements.txt
  benchmark_test/scripts/test_main.py
Labels: size/M, benchmark

#903 Modify benchmark script
  benchmark_test/scripts/milvus_helpers.py
Labels: size/XS, benchmark

#904 Update encode.py for towhee 0.2
  solutions/reverse_image_search/quick_deploy/server/requirements.txt
  solutions/reverse_image_search/quick_deploy/server/src/encode.py
Labels: size/XS, reverse_image_search/quick_deploy

#898 Add test for molsearch
  solutions/molecular_similarity_search/quick_deploy/server/requirements.txt
  solutions/molecular_similarity_search/quick_deploy/server/src/encode.py
  solutions/molecular_similarity_search/quick_deploy/server/src/logs.py
  solutions/molecular_similarity_search/quick_deploy/server/src/main.py
  solutions/molecular_similarity_search/quick_deploy/server/src/operations/count.py
  solutions/molecular_similarity_search/quick_deploy/server/src/operations/drop.py
  solutions/molecular_similarity_search/quick_deploy/server/src/operations/load.py
  solutions/molecular_similarity_search/quick_deploy/server/src/operations/search.py
  solutions/molecular_similarity_search/quick_deploy/server/src/test_main.py
Labels: size/L, molecular_similarity_search/quick_deploy

#907 Update quick-deploy for image-object-detection with towhee pipelines
  solutions/reverse_image_search/object_detection/server/requirements.txt
  solutions/reverse_image_search/object_detection/server/src/config.py
  solutions/reverse_image_search/object_detection/server/src/encode.py
  solutions/reverse_image_search/object_detection/server/src/encode_resnet50.py
  solutions/reverse_image_search/object_detection/server/src/main.py
  solutions/reverse_image_search/object_detection/server/src/milvus_helpers.py
  solutions/reverse_image_search/object_detection/server/src/mysql_helpers.py
  solutions/reverse_image_search/object_detection/server/src/operations/load.py
  solutions/reverse_image_search/object_detection/server/src/operations/search.py
Labels: size/L

#908 Add test script for image object detection
  solutions/reverse_image_search/object_detection/server/requirements.txt
  solutions/reverse_image_search/object_detection/server/src/config.py
  solutions/reverse_image_search/object_detection/server/src/test_main.py
Labels: size/M, reverse_image_search/object_detection

#911 Add test for mols docker-compose
  solutions/molecular_similarity_search/quick_deploy/test_docker_compose.py
Labels: size/M

#912 Update video object detection for towhee pipelines
  solutions/video_similarity_search/object_detection/server/requirements.txt
  solutions/video_similarity_search/object_detection/server/src/config.py
  solutions/video_similarity_search/object_detection/server/src/encode.py
  solutions/video_similarity_search/object_detection/server/src/encode_resnet50.py
  solutions/video_similarity_search/object_detection/server/src/frame_extract.py
  solutions/video_similarity_search/object_detection/server/src/main.py
  solutions/video_similarity_search/object_detection/server/src/operations/search.py
Labels: size/L

#913 Update requirements
  solutions/video_similarity_search/object_detection/server/requirements.txt
Labels: size/XS

#914 Update deploy-ci to install ffmpeg
  .github/workflows/deploy_ci.yml
Labels: size/XS

#910 Add docker-compose.yaml for molsearch
  solutions/molecular_similarity_search/docker-compose.yaml
  solutions/molecular_similarity_search/quick_deploy/molsearch-docker-compose.yaml
  solutions/molecular_similarity_search/quick_deploy/server/Dockerfile
Labels: size/L

#919 Add docker_compose ci
  .github/workflows/docker_compose_ci.yml
Labels: size/M

#917 update README.md
  solutions/text_search_engine/quick_deploy/README.md
Labels: size/S

#916 Update README for towhee
  solutions/reverse_image_search/object_detection/README.md
  solutions/reverse_image_search/quick_deploy/README.md
Labels: size/S

#920 fix bug
  solutions/molecular_similarity_search/quick_deploy/client/src/containers/Setting.tsx
Labels: size/XS

#924 Update Dockerfile of mols-search-webclient
  solutions/molecular_similarity_search/quick_deploy/client/Dockerfile
Labels: size/XS

#922 Update docker_compose_ci.yml
  .github/workflows/docker_compose_ci.yml
Labels: size/XS

#923 Update the version of mols-search-webclient:2.0
  solutions/molecular_similarity_search/quick_deploy/molsearch-docker-compose.yaml
Labels: size/XS, docker-compose

#915 Debug test_client.py
  solutions/recommender_system/quick_deploy/movie_recommender/test_client.py
Labels: size/XS

#921 Update readme for video object detection with towhee
  solutions/video_similarity_search/object_detection/README.md
Labels: size/M

#927 Replace encoder with towhee
  solutions/video_similarity_search/quick_deploy/server/requirements.txt
  solutions/video_similarity_search/quick_deploy/server/src/config.py
  solutions/video_similarity_search/quick_deploy/server/src/encode.py
  solutions/video_similarity_search/quick_deploy/server/src/operations/load.py
  solutions/video_similarity_search/quick_deploy/server/src/resnet50_encode.py
  solutions/video_similarity_search/quick_deploy/server/src/test_main.py
Labels: size/M, video_similarity_search/quick_deploy

#928 Update deploy_ci.yml
  .github/workflows/deploy_ci.yml
Labels: size/XS

#929 Update Docker ci
  .github/workflows/docker_compose_ci.yml
Labels: size/S

#933 Update readme for some notes
  solutions/reverse_image_search/quick_deploy/README.md
Labels: size/S

#930 Update readme of video analysis
  solutions/video_similarity_search/quick_deploy/README.md
Labels: size/S

#931 Update main.py for front-end to get image
  solutions/reverse_image_search/quick_deploy/server/src/main.py
  solutions/reverse_image_search/quick_deploy/server/src/test_main.py
Labels: size/S, reverse_image_search/quick_deploy

#926 Milvus3D initial commit
  solutions/milvus3d/README.md
  solutions/milvus3d/quick_deploy/server/data/compress.py
  solutions/milvus3d/quick_deploy/server/data/download_data.sh
  solutions/milvus3d/quick_deploy/server/data/preprocess.sh
  solutions/milvus3d/quick_deploy/server/data/preprocess_npy.py
  solutions/milvus3d/quick_deploy/server/data/test_download_data.sh
  solutions/milvus3d/quick_deploy/server/requirements.txt
  solutions/milvus3d/quick_deploy/server/src/config.py
  solutions/milvus3d/quick_deploy/server/src/encode.py
  solutions/milvus3d/quick_deploy/server/src/logs.py
  solutions/milvus3d/quick_deploy/server/src/main.py
  solutions/milvus3d/quick_deploy/server/src/milvus3d/MeshNet.py
  solutions/milvus3d/quick_deploy/server/src/milvus3d/layers.py
  solutions/milvus3d/quick_deploy/server/src/milvus3d/transform.py
  solutions/milvus3d/quick_deploy/server/src/milvus_helpers.py
  solutions/milvus3d/quick_deploy/server/src/mysql_helpers.py
  solutions/milvus3d/quick_deploy/server/src/operations/__init__.py
  solutions/milvus3d/quick_deploy/server/src/operations/count.py
  solutions/milvus3d/quick_deploy/server/src/operations/drop.py
  solutions/milvus3d/quick_deploy/server/src/operations/load.py
  solutions/milvus3d/quick_deploy/server/src/operations/search.py
  solutions/milvus3d/quick_deploy/server/src/operations/upload.py
  solutions/milvus3d/quick_deploy/server/src/test_main.py
Labels: size/XXL, milvus3d/quick_deploy

#940 Update docker ci to mkdir data
  .github/workflows/docker_compose_ci.yml
Labels: size/XS

#942 Update docker_compose_ci
  .github/workflows/docker_compose_ci.yml
Labels: size/XS

#939 Update README of audio
  solutions/audio_similarity_search/quick_deploy/README.md
  solutions/audio_similarity_search/quick_deploy/pic/searchgui.png
Labels: size/L

#934 Update the README of molecular
  solutions/molecular_similarity_search/quick_deploy/README.md
Labels: size/L

#935 Update Dockerfile of audio
  solutions/audio_similarity_search/quick_deploy/server/Dockerfile
Labels: size/XS

#936 Update img-search image tag
  solutions/reverse_image_search/quick_deploy/README.md
Labels: size/XS

#937 Fix recommender
  solutions/recommender_system/quick_deploy/movie_recommender/as.py
  solutions/recommender_system/quick_deploy/movie_recommender/cm.py
  solutions/recommender_system/quick_deploy/movie_recommender/rank.py
  solutions/recommender_system/quick_deploy/movie_recommender/recall.py
  solutions/recommender_system/quick_deploy/movie_recommender/um.py
  solutions/recommender_system/requirements.txt
Labels: size/S

#938 Update Dockerfile for new docker image
  solutions/reverse_image_search/quick_deploy/server/Dockerfile
Labels: size/S

#943 Add docker-compose yaml and test script
  solutions/reverse_image_search/quick_deploy/docker-compose.yaml
  solutions/reverse_image_search/quick_deploy/test_docker_compose.py
Labels: size/L, docker-compose

#944 Add docker-compose yaml and test script for image object detection
  solutions/reverse_image_search/object_detection/docker-compose.yaml
  solutions/reverse_image_search/object_detection/server/Dockerfile
  solutions/reverse_image_search/object_detection/test_docker_compose.py
Labels: docker-compose

#946 Update README for new way to start servers
  solutions/reverse_image_search/quick_deploy/README.md
Labels: size/L

#947 Update readme
  solutions/reverse_image_search/quick_deploy/README.md
Labels: size/M

#948 Update README
  solutions/reverse_image_search/object_detection/README.md
Labels: size/L

#950 Update jupyter_ci.yml
  .github/workflows/jupyter_ci.yml
Labels: size/XS

#952 Correct typo in requirements file name
  solutions/text_search_engine/quick_deploy/README.md
Labels: size/XS

#953 Update jupyter ci
  .github/workflows/jupyter_ci.yml
Labels: size/XS

#954 Update jupyter_ci.yml
  .github/workflows/jupyter_ci.yml
Labels: size/XS

#945 Initial commit jupyter notebook
  solutions/milvus3d/jupyter_notebook/data/compress.py
  solutions/milvus3d/jupyter_notebook/data/download_data.sh
  solutions/milvus3d/jupyter_notebook/data/preprocess.sh
  solutions/milvus3d/jupyter_notebook/data/preprocess_npy.py
  solutions/milvus3d/jupyter_notebook/milvus3d/MeshNet.py
  solutions/milvus3d/jupyter_notebook/milvus3d/layers.py
  solutions/milvus3d/jupyter_notebook/milvus3d/transform.py
  solutions/milvus3d/jupyter_notebook/milvus3d_demo.ipynb
  solutions/milvus3d/jupyter_notebook/notebook_config.py
  solutions/milvus3d/jupyter_notebook/requirements.jupyter.txt
Labels: jupyter, size/XXL

#956 Update README of molsearch
  solutions/molecular_similarity_search/quick_deploy/README.md
Labels: size/XS

#958 Slim video-analysis
  solutions/video_similarity_search/pic/load.png
  solutions/video_similarity_search/pic/search.png
  solutions/video_similarity_search/pic/show.png
Labels: size/XS

#959 Update UPLOAD_PATH and scripts
  solutions/video_similarity_search/object_detection/server/src/config.py
  solutions/video_similarity_search/object_detection/server/src/main.py
Labels: size/S, video_similarity_search/object_detection

#964 Update README of molsearch
  solutions/molecular_similarity_search/quick_deploy/README.md
Labels: size/XS

#955 Update README of audio search
  solutions/audio_similarity_search/quick_deploy/README.md
Labels: size/S

#962 update code and add docker-compose.yaml
  solutions/text_search_engine/quick_deploy/client/Dockerfile
  solutions/text_search_engine/quick_deploy/client/yarn.lock
  solutions/text_search_engine/quick_deploy/docker-compose.yaml
  solutions/text_search_engine/quick_deploy/server/Dockerfile
  solutions/text_search_engine/quick_deploy/server/requirements.txt
  solutions/text_search_engine/quick_deploy/server/src/main.py
  solutions/text_search_engine/quick_deploy/server/src/test_main.py
  solutions/text_search_engine/quick_deploy/test_docker_compose.py
Labels: size/XXL, docker-compose

#961 update dockerfile and docker-compose
  solutions/video_similarity_search/quick_deploy/docker-compose.yaml
  solutions/video_similarity_search/quick_deploy/server/Dockerfile
  solutions/video_similarity_search/quick_deploy/test_docker_compose.py
Labels: size/L, docker-compose

#975 update video readme
  solutions/video_similarity_search/quick_deploy/README.md
Labels: size/M

#973 update text readme
  solutions/text_search_engine/quick_deploy/README.md
Labels: size/M

#972 update video docker file
  solutions/video_similarity_search/object_detection/Dockerfile
  solutions/video_similarity_search/object_detection/README.md
  solutions/video_similarity_search/object_detection/docker-compose.yaml
  solutions/video_similarity_search/object_detection/test_docker_compose.py
Labels: size/L, docker-compose

#976 update video similarity search Readme
  solutions/video_similarity_search/quick_deploy/README.md
Labels: size/S

#978 update video Readme
  solutions/video_similarity_search/quick_deploy/README.md
Labels: size/XS

#977 update video search README.md
  solutions/video_similarity_search/object_detection/README.md
Labels: size/M
