Repository milvus-io/bootcamp, pull requests merged in 2021-09, with the labels that each got.

#614 update qa-chatbot to Milvus2.0.0-rc5
  solutions/question_answering_system/question_answering.ipynb
  solutions/question_answering_system/quick_deploy/README.md
  solutions/question_answering_system/quick_deploy/server/.idea/.gitignore
  solutions/question_answering_system/quick_deploy/server/.idea/inspectionProfiles/Project_Default.xml
  solutions/question_answering_system/quick_deploy/server/.idea/inspectionProfiles/profiles_settings.xml
  solutions/question_answering_system/quick_deploy/server/.idea/misc.xml
  solutions/question_answering_system/quick_deploy/server/.idea/modules.xml
  solutions/question_answering_system/quick_deploy/server/.idea/server.iml
  solutions/question_answering_system/quick_deploy/server/.idea/vcs.xml
  solutions/question_answering_system/quick_deploy/server/requirements.txt
  solutions/question_answering_system/quick_deploy/server/src/milvus_helpers.py
  solutions/question_answering_system/requirements.txt
Labels: size/L

#628 update Milvus 2.0 rc5（text_search）
  solutions/question_answering_system/question_answering.ipynb
  solutions/text_search_engine/.vscode/sftp.json
  solutions/text_search_engine/quick_deploy/server/requirement.txt
  solutions/text_search_engine/quick_deploy/server/src/milvus_helpers.py
  solutions/text_search_engine/requirements.txt
  solutions/text_search_engine/text_search_engine .ipynb
Labels: size/L

#625 update reverse image search for milvus 2.0-rc5
  README.md
  solutions/README.md
  solutions/reverse_image_search/object_detection/README.md
  solutions/reverse_image_search/object_detection/server/requirements.txt
  solutions/reverse_image_search/object_detection/server/src/milvus_helpers.py
  solutions/reverse_image_search/quick_deploy/README.md
  solutions/reverse_image_search/quick_deploy/server/requirements.txt
  solutions/reverse_image_search/quick_deploy/server/src/milvus_helpers.py
  solutions/reverse_image_search/requirements.txt
  solutions/reverse_image_search/reverse_image_search.ipynb
  solutions/video_similarity_search/object_detection/README.md
  solutions/video_similarity_search/object_detection/server/requirements.txt
  solutions/video_similarity_search/object_detection/server/src/milvus_helpers.py
  solutions/video_similarity_search/quick_deploy/README.md
  solutions/video_similarity_search/quick_deploy/server/requirements.txt
  solutions/video_similarity_search/quick_deploy/server/src/milvus_helpers.py
  solutions/video_similarity_search/requirements.txt
  solutions/video_similarity_search/video_similarity_search.ipynb
Labels: size/L

#630 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: size/M

#629 Update Recommendation System to v2-rc5
  solutions/recommendation_system/quick_deploy/movie_recommender/milvus_tool/README.md
  solutions/recommendation_system/quick_deploy/movie_recommender/milvus_tool/config.py
  solutions/recommendation_system/quick_deploy/movie_recommender/milvus_tool/milvus_insert.py
  solutions/recommendation_system/quick_deploy/movie_recommender/milvus_tool/milvus_recall.py
  solutions/recommendation_system/recommendation_system.ipynb
  solutions/recommendation_system/requirements.txt
Labels: size/XL

#631 Update "about"
  README.md
Labels: size/XS

#633 mols search 2.0.0rc-5 update
  solutions/molecular_similarity_search/docker-compose.yaml
  solutions/molecular_similarity_search/molecular_search.ipynb
  solutions/molecular_similarity_search/quick_deploy/server/requirements.txt
  solutions/molecular_similarity_search/quick_deploy/server/src/helpers/milvus_helpers.py
  solutions/molecular_similarity_search/requirements.txt
Labels: size/L

#634 Update audio search to rc5
  solutions/audio_similarity_search/audio_similarity_search.ipynb
  solutions/audio_similarity_search/quick_deploy/server/requirements.txt
  solutions/audio_similarity_search/quick_deploy/server/src/milvus_helpers.py
  solutions/audio_similarity_search/requirements.txt
Labels: size/M

#632 Update milvus_helpers.py
  solutions/text_search_engine/quick_deploy/server/src/milvus_helpers.py
Labels: size/XS

#642 Update live demo on README
  README.md
Labels: size/M

#645 Solve the issue: https://github.com/milvus-io/bootcamp/issues/635
  solutions/reverse_image_search/quick_deploy/server/requirements.txt
Labels: size/XS

#646 Modified a small bug in extracting features
  solutions/reverse_image_search/quick_deploy/server/src/operations/load.py
Labels: size/S

#648 Update README.md
  README.md
Labels: size/XS

#652 update text_search_engine notebook name
  solutions/text_search_engine/text_search_engine.ipynb
Labels: size/XS

#655 Changed all "Recommendation system" to "recommender systems" #649
  README.md
  solutions/README.md
  solutions/recommendation_system/README.md
  solutions/recommender_system/README.md
  solutions/recommender_system/quick_deploy/README.md
  solutions/recommender_system/quick_deploy/movie_recommender/as.py
  solutions/recommender_system/quick_deploy/movie_recommender/cm.py
  solutions/recommender_system/quick_deploy/movie_recommender/get_data.sh
  solutions/recommender_system/quick_deploy/movie_recommender/milvus_tool/README.md
  solutions/recommender_system/quick_deploy/movie_recommender/milvus_tool/config.py
  solutions/recommender_system/quick_deploy/movie_recommender/milvus_tool/milvus_insert.py
  solutions/recommender_system/quick_deploy/movie_recommender/milvus_tool/milvus_recall.py
  solutions/recommender_system/quick_deploy/movie_recommender/proto/__init__.py
  solutions/recommender_system/quick_deploy/movie_recommender/proto/as.proto
  solutions/recommender_system/quick_deploy/movie_recommender/proto/cm.proto
  solutions/recommender_system/quick_deploy/movie_recommender/proto/item_info.proto
  solutions/recommender_system/quick_deploy/movie_recommender/proto/rank.proto
  solutions/recommender_system/quick_deploy/movie_recommender/proto/recall.proto
  solutions/recommender_system/quick_deploy/movie_recommender/proto/run_codegen.py
  solutions/recommender_system/quick_deploy/movie_recommender/proto/um.proto
  solutions/recommender_system/quick_deploy/movie_recommender/proto/user_info.proto
  solutions/recommender_system/quick_deploy/movie_recommender/rank.py
  solutions/recommender_system/quick_deploy/movie_recommender/recall.py
  solutions/recommender_system/quick_deploy/movie_recommender/start_server.sh
  solutions/recommender_system/quick_deploy/movie_recommender/test_client.py
  solutions/recommender_system/quick_deploy/movie_recommender/to_milvus.py
  solutions/recommender_system/quick_deploy/movie_recommender/to_redis.py
  solutions/recommender_system/quick_deploy/movie_recommender/um.py
  solutions/recommender_system/recommender_system.ipynb
  solutions/recommender_system/requirements.txt
Labels: size/XL

#654 Update quick-deploy for video object detection
  solutions/video_similarity_search/object_detection/README.md
  solutions/video_similarity_search/object_detection/client/env.config.js
  solutions/video_similarity_search/object_detection/pic/fastapi.png
  solutions/video_similarity_search/object_detection/pic/web1.png
  solutions/video_similarity_search/object_detection/pic/web2.png
  solutions/video_similarity_search/object_detection/pic/web3.png
  solutions/video_similarity_search/object_detection/pic/web4.png
  solutions/video_similarity_search/object_detection/pic/web5.png
  solutions/video_similarity_search/object_detection/server/requirements.txt
  solutions/video_similarity_search/object_detection/server/src/main.py
Labels: size/L

#657 record whether the user uploads
  solutions/video_similarity_search/object_detection/client/src/components/sideBar.tsx
  solutions/video_similarity_search/object_detection/client/src/pages/home.tsx
Labels: size/S

#656 Video object detect server
  solutions/video_similarity_search/object_detection/README.md
Labels: size/M

#659 Video object detect server
  solutions/video_similarity_search/object_detection/README.md
  solutions/video_similarity_search/object_detection/server/src/config.py
Labels: size/S

#661 Added description for index progress option
  benchmark_test/scripts/README.md
Labels: size/XS

#662 [skip ci] Add Milvus x Hacktoberfest banner
  README.md
Labels: size/XS

#665 Update Milvus helper for DNA
  solutions/dna_sequence_classification/quick_deploy/server/src/milvus_helpers.py
Labels: size/XS

#663 Add comment
  solutions/reverse_image_search/quick_deploy/server/src/milvus_helpers.py
Labels: size/XS

#664 Add comment for audio similarity search
  solutions/audio_similarity_search/quick_deploy/server/src/milvus_helpers.py
Labels: size/XS

#666 Update Milvus helper for mol search
  solutions/molecular_similarity_search/quick_deploy/server/src/helpers/milvus_helpers.py
Labels: size/XS

#668 Format code for recommender system
  solutions/recommender_system/quick_deploy/movie_recommender/to_milvus.py
Labels: size/XS

#672 add punctuation
  solutions/reverse_image_search/quick_deploy/README.md
Labels: size/XS

#673 add comments for image search
  solutions/reverse_image_search/quick_deploy/server/src/main.py
Labels: size/XS

#669 Update the version of tensorflow
  solutions/video_similarity_search/quick_deploy/server/requirements.txt
Labels: size/XS

#674 Stop printing out the first search result
  solutions/video_similarity_search/object_detection/server/src/milvus_helpers.py
Labels: size/XS

#671 Update video_object_detection config.py
  solutions/video_similarity_search/object_detection/server/src/config.py
Labels: size/XS

#667 Update README about object similarity searchSigned-off-by: shiyu22 sh…
  solutions/video_similarity_search/README.md
Labels: size/XS

#675 Add comment for image search proj
  solutions/reverse_image_search/object_detection/server/src/main.py
Labels: size/XS

#670 Update the comments of config
  benchmark_test/scripts/config.py
Labels: size/S

#676 Update README.md
  solutions/text_search_engine/quick_deploy/README.md
Labels: size/XS

#678 update README.md
  solutions/text_search_engine/quick_deploy/README.md
Labels: size/XS

#682 Fix typo in qa_system/quick-deploy/readme
  solutions/question_answering_system/quick_deploy/README.md
Labels: size/S

#681 Change a french word to english
  solutions/question_answering_system/README.md
Labels: size/XS

#685 Update contributing content
  contributing.md
Labels: size/XS

#684 Update PR_template
  .github/pull_request_template.md
Labels: size/XS

#683 update .gitattributes
  .gitattributes
Labels: size/XS

#687 Update main.py
  benchmark_test/scripts/main.py
Labels: size/XS

#686 Update load.py
  benchmark_test/scripts/load.py
Labels: size/XS

#688 Update load.py
  benchmark_test/scripts/load.py
Labels: size/XS

#689 Delete RNSG index
  benchmark_test/scripts/load.py
Labels: size/XS

#690 Update benchmark to rc6
  benchmark_test/scripts/requirements.txt
Labels: size/XS

#692 Update milvus_helpers.py
  benchmark_test/scripts/milvus_helpers.py
Labels: size/XS

#691 Update README.md
  benchmark_test/scripts/README.md
Labels: size/XS

#694 Update encode.py
  solutions/reverse_image_search/quick_deploy/server/src/encode.py
Labels: size/XS

#697 Remove useless line
  solutions/video_similarity_search/object_detection/server/src/encode.py
Labels: size/XS

#696 Add comments on audio-encoder
  solutions/audio_similarity_search/quick_deploy/server/main.py
  solutions/audio_similarity_search/quick_deploy/server/src/config.py
Labels: size/XS

#695 Delete useless black line
  solutions/audio_similarity_search/quick_deploy/server/main.py
Labels: size/XS

#699 Modify wrong link for installing Milvus
  benchmark_test/lab1_sift1b_1m.md
Labels: size/XS

#698 Modify the wrong link for installing Milvus
  benchmark_test/lab1_sift1b_1m.md
Labels: size/XS

#712 Update README of video object detection
  solutions/video_similarity_search/object_detection/README.md
Labels: size/M

#714 update gitingore
  .gitignore
Labels: size/XS

#713 Modify the description of EXTERNAL_DATAPATH
  solutions/audio_similarity_search/quick_deploy/README.md
Labels: size/XS

#710 Update PR template
  .github/pull_request_template.md
Labels: size/XS

#711 Rename the EXTERNAL_DATAPATH parameter
  solutions/molecular_similarity_search/quick_deploy/README.md
Labels: size/XS

#715 add multi_thread_insert test script
  benchmark_test/concurrent-test/multi_process_insert.py
Labels: size/M

#716 [skip ci] Fix grammar
  README.md
Labels: size/XS

#718 change concurrent insert script
  benchmark_test/concurrent-test/multi_process_insert.py
Labels: size/M

#717 [skip ci] Fix grammar
  solutions/README.md
Labels: size/XS
