Repository milvus-io/bootcamp, pull requests merged in 2022-04, with the labels that each got.

#1041 Fix Chinese garbled code and code missed
  solutions/question_answering_system/quick_deploy/server/src/milvus_helpers.py
  solutions/question_answering_system/quick_deploy/server/src/mysql_helpers.py
Labels: size/XS

#1046 Update to Milvus2.0.2 and Towhee0.6
  solutions/reverse_image_search/object_detection/README.md
  solutions/reverse_image_search/object_detection/docker-compose.yaml
  solutions/reverse_image_search/object_detection/server/__init__.py
  solutions/reverse_image_search/object_detection/server/requirements.txt
  solutions/reverse_image_search/object_detection/server/src/config.py
  solutions/reverse_image_search/object_detection/server/src/encode.py
  solutions/reverse_image_search/object_detection/server/src/encode_resnet50.py
  solutions/reverse_image_search/object_detection/server/src/main.py
  solutions/reverse_image_search/object_detection/server/src/yolov3_detector/__init__.py
  solutions/reverse_image_search/object_detection/server/src/yolov3_detector/data/prepare_model.sh
  solutions/reverse_image_search/object_detection/server/src/yolov3_detector/paddle_yolo.py
  solutions/reverse_image_search/object_detection/server/src/yolov3_detector/yolo_infer.py
  solutions/reverse_image_search/object_detection/test_docker_compose.py
  solutions/reverse_image_search/quick_deploy/README.md
  solutions/reverse_image_search/quick_deploy/docker-compose.yaml
  solutions/reverse_image_search/quick_deploy/server/Dockerfile
  solutions/reverse_image_search/quick_deploy/server/requirements.txt
  solutions/reverse_image_search/quick_deploy/server/src/config.py
  solutions/reverse_image_search/quick_deploy/server/src/encode.py
  solutions/reverse_image_search/quick_deploy/server/src/encode_tf_resnet50.py
  solutions/video_similarity_search/object_detection/README.md
  solutions/video_similarity_search/object_detection/docker-compose.yaml
  solutions/video_similarity_search/object_detection/server/Dockerfile
  solutions/video_similarity_search/object_detection/server/requirements.txt
  solutions/video_similarity_search/object_detection/server/src/config.py
  solutions/video_similarity_search/object_detection/server/src/encode.py
  solutions/video_similarity_search/object_detection/server/src/encode_resnet50.py
  solutions/video_similarity_search/object_detection/server/src/yolov3_detector/__init__.py
  solutions/video_similarity_search/object_detection/server/src/yolov3_detector/data/prepare_model.sh
  solutions/video_similarity_search/object_detection/server/src/yolov3_detector/paddle_yolo.py
  solutions/video_similarity_search/object_detection/server/src/yolov3_detector/yolo_infer.py
  solutions/video_similarity_search/object_detection/test_docker_compose.py
  solutions/video_similarity_search/quick_deploy/README.md
  solutions/video_similarity_search/quick_deploy/docker-compose.yaml
  solutions/video_similarity_search/quick_deploy/server/requirements.txt
  solutions/video_similarity_search/quick_deploy/server/src/config.py
  solutions/video_similarity_search/quick_deploy/server/src/encode.py
  solutions/video_similarity_search/quick_deploy/server/src/resnet50_encode.py
  solutions/video_similarity_search/quick_deploy/server/src/test_main.py
  solutions/video_similarity_search/quick_deploy/test_docker_compose.py
Labels: size/XXL, docker-compose, lgtm

#1047 Update notebook for Milvus2.0.2 & Towhee 0.6.0
  solutions/reverse_image_search/requirements.txt
  solutions/reverse_image_search/reverse_image_search.ipynb
Labels: jupyter, size/XL

#1048 Replace normalization with Towhee APIs
  solutions/reverse_image_search/object_detection/server/src/encode.py
  solutions/reverse_image_search/quick_deploy/server/src/encode.py
  solutions/reverse_image_search/reverse_image_search.ipynb
Labels: reverse_image_search/quick_deploy, size/L

#1049 Update for exception safe in towhee dc
  solutions/reverse_image_search/reverse_image_search.ipynb
Labels: size/XS
