Repository milvus-io/bootcamp, pull requests merged in 2022-09, with the labels that each got.

#1077 fix: Image retrieval client failed to compile #1076
  solutions/reverse_image_search/quick_deploy/client/package-lock.json
  solutions/reverse_image_search/quick_deploy/client/package.json
Labels: size/XXL

#1078 fix: Image retrieval client docker image fails to build
  solutions/reverse_image_search/quick_deploy/client/.dockerignore
  solutions/reverse_image_search/quick_deploy/client/Dockerfile
Labels: size/S

#1079 Add one step tutorial in reverse image search
  solutions/reverse_image_search/.idea/workspace.xml
  solutions/reverse_image_search/one_step/server/__init__.py
  solutions/reverse_image_search/one_step/server/config.py
  solutions/reverse_image_search/one_step/server/encode.py
  solutions/reverse_image_search/one_step/server/logs.py
  solutions/reverse_image_search/one_step/server/main.py
  solutions/reverse_image_search/one_step/server/milvus_helpers.py
  solutions/reverse_image_search/one_step/server/operators.py
  solutions/reverse_image_search/one_step/server/requirements.txt
Labels: size/XL

#1080 Add README
  solutions/reverse_image_search/one_step/README.md
  solutions/reverse_image_search/one_step/server/encode.py
Labels: size/XS

#1074 Update README
  README.md
Labels: size/L

#1081 feat: add one-step client
  solutions/reverse_image_search/one_step/client/.dockerignore
  solutions/reverse_image_search/one_step/client/.env
  solutions/reverse_image_search/one_step/client/.gitignore
  solutions/reverse_image_search/one_step/client/README.md
  solutions/reverse_image_search/one_step/client/docker/Dockerfile.base
  solutions/reverse_image_search/one_step/client/docker/Dockerfile.nginx
  solutions/reverse_image_search/one_step/client/docker/Dockerfile.standalone
  solutions/reverse_image_search/one_step/client/docker/nginx/conf/conf.d/client.conf
  solutions/reverse_image_search/one_step/client/docker/nginx/conf/conf.d/gzip.conf
  solutions/reverse_image_search/one_step/client/docker/standalone/main.go
  solutions/reverse_image_search/one_step/client/env-config.js
  solutions/reverse_image_search/one_step/client/env.sh
  solutions/reverse_image_search/one_step/client/package-lock.json
  solutions/reverse_image_search/one_step/client/package.json
  solutions/reverse_image_search/one_step/client/public/favicon.png
  solutions/reverse_image_search/one_step/client/public/index.html
  solutions/reverse_image_search/one_step/client/src/App.css
  solutions/reverse_image_search/one_step/client/src/App.tsx
  solutions/reverse_image_search/one_step/client/src/components/Gallary.tsx
  solutions/reverse_image_search/one_step/client/src/components/SearchResults.jsx
  solutions/reverse_image_search/one_step/client/src/components/SeperatLine.tsx
  solutions/reverse_image_search/one_step/client/src/containers/Logo.svg
  solutions/reverse_image_search/one_step/client/src/containers/Setting.tsx
  solutions/reverse_image_search/one_step/client/src/contexts/QueryContext.tsx
  solutions/reverse_image_search/one_step/client/src/index.css
  solutions/reverse_image_search/one_step/client/src/index.tsx
  solutions/reverse_image_search/one_step/client/src/logo.svg
  solutions/reverse_image_search/one_step/client/src/react-app-env.d.ts
  solutions/reverse_image_search/one_step/client/src/setupTests.ts
  solutions/reverse_image_search/one_step/client/src/utils/CreateStyle.ts
  solutions/reverse_image_search/one_step/client/src/utils/Endpoints.ts
  solutions/reverse_image_search/one_step/client/src/utils/Helper.ts
  solutions/reverse_image_search/one_step/client/src/utils/color.ts
  solutions/reverse_image_search/one_step/client/tsconfig.json
Labels: size/XXL

#1082 feat: add one-step base image, milvus embeded
  solutions/reverse_image_search/one_step/README.md
  solutions/reverse_image_search/one_step/docker/Dockerfile.milvus
  solutions/reverse_image_search/one_step/docker/milvus/config.yml
  solutions/reverse_image_search/one_step/docker/milvus/entrypoint.sh
  solutions/reverse_image_search/one_step/docker/milvus/hello-world.py
Labels: size/XL

#1083 feat: add one-step server image
  solutions/reverse_image_search/one_step/README.md
  solutions/reverse_image_search/one_step/docker/Dockerfile.server
Labels: size/M

#1084 feat: Add `one-step` All In One docker image
  solutions/reverse_image_search/one_step/README.md
  solutions/reverse_image_search/one_step/client/docker/standalone/main.go
  solutions/reverse_image_search/one_step/docker/Dockerfile
  solutions/reverse_image_search/one_step/docker/Dockerfile.client
Labels: size/M

#1085 fix: one step docker image
  solutions/reverse_image_search/one_step/.gitignore
  solutions/reverse_image_search/one_step/README.md
  solutions/reverse_image_search/one_step/client/config-overrides.js
  solutions/reverse_image_search/one_step/client/docker/Dockerfile.debian
  solutions/reverse_image_search/one_step/client/docker/Dockerfile.standalone
  solutions/reverse_image_search/one_step/client/docker/standalone/go.mod
  solutions/reverse_image_search/one_step/client/docker/standalone/go.sum
  solutions/reverse_image_search/one_step/client/docker/standalone/main.go
  solutions/reverse_image_search/one_step/client/package-lock.json
  solutions/reverse_image_search/one_step/client/package.json
  solutions/reverse_image_search/one_step/client/public/index.html
  solutions/reverse_image_search/one_step/client/src/components/Gallary.tsx
  solutions/reverse_image_search/one_step/client/src/index.css
  solutions/reverse_image_search/one_step/client/src/index.tsx
  solutions/reverse_image_search/one_step/client/src/setupTests.ts
Labels: size/L

#1090 chore: improve docker build speed
  solutions/reverse_image_search/one_step/client/docker/Dockerfile.debian
  solutions/reverse_image_search/one_step/docker/Dockerfile.server
Labels: size/XS

#1097 fix: Complete opencv dependencies
  solutions/reverse_image_search/one_step/docker/Dockerfile
  solutions/reverse_image_search/one_step/docker/Dockerfile.server
Labels: size/XS

#1098 chore: improve client docker
  solutions/reverse_image_search/one_step/README.md
  solutions/reverse_image_search/one_step/client/docker/Dockerfile
  solutions/reverse_image_search/one_step/client/docker/Dockerfile.base
  solutions/reverse_image_search/one_step/client/docker/Dockerfile.nginx
  solutions/reverse_image_search/one_step/client/docker/Dockerfile.standalone
  solutions/reverse_image_search/one_step/client/docker/standalone/main.go
Labels: size/M

#1099 feat: one-step docker online log viewer
  solutions/reverse_image_search/one_step/README.md
  solutions/reverse_image_search/one_step/docker/Dockerfile
Labels: size/S

#1100 feat: one-step web console
  solutions/reverse_image_search/one_step/README.md
  solutions/reverse_image_search/one_step/docker/Dockerfile
Labels: size/S

#1102 feat: easier to use, reduce ports
  solutions/reverse_image_search/one_step/README.md
  solutions/reverse_image_search/one_step/client/docker/standalone/main.go
  solutions/reverse_image_search/one_step/client/src/containers/Setting.tsx
  solutions/reverse_image_search/one_step/docker/Dockerfile
Labels: size/M

#1101 fix: one step client logical problem
  solutions/reverse_image_search/one_step/client/src/containers/Setting.tsx
Labels: size/S

#1103 Readme one
  solutions/reverse_image_search/README.md
  solutions/reverse_image_search/one_step/README.md
  solutions/reverse_image_search/one_step/client/docker/Dockerfile.client
  solutions/reverse_image_search/one_step/workflow.png
Labels: size/M

#1105 chore: Adjust how links are opened
  solutions/reverse_image_search/one_step/client/src/containers/Setting.tsx
Labels: size/XS

#1107 fix: fix fixed value
  solutions/reverse_image_search/one_step/client/src/containers/Setting.tsx
Labels: size/XS

#1094 fix: question answering system #1093
  solutions/question_answering_system/quick_deploy/client/.dockerignore
  solutions/question_answering_system/quick_deploy/client/.gitignore
  solutions/question_answering_system/quick_deploy/client/Dockerfile
  solutions/question_answering_system/quick_deploy/client/nginx/conf/conf.d/client.conf
  solutions/question_answering_system/quick_deploy/client/nginx/conf/conf.d/gzip.conf
  solutions/question_answering_system/quick_deploy/client/package-lock.json
  solutions/question_answering_system/quick_deploy/client/package.json
  solutions/question_answering_system/quick_deploy/client/yarn.lock
Labels: size/XXL

#1092 fix: molecular similarity search #1091
  solutions/molecular_similarity_search/quick_deploy/client/.dockerignore
  solutions/molecular_similarity_search/quick_deploy/client/Dockerfile
  solutions/molecular_similarity_search/quick_deploy/client/nginx/conf/conf.d/client.conf
  solutions/molecular_similarity_search/quick_deploy/client/nginx/conf/conf.d/gzip.conf
  solutions/molecular_similarity_search/quick_deploy/client/package-lock.json
  solutions/molecular_similarity_search/quick_deploy/client/package.json
Labels: size/XXL
