Repository milvus-io/bootcamp, pull requests merged in 2022-01, with the labels that each got.

#998 fix molecular search web client healthcheck
  solutions/molecular_similarity_search/quick_deploy/client/Dockerfile
  solutions/molecular_similarity_search/quick_deploy/molsearch-docker-compose.yaml
Labels: size/XS

#993 fix audio-client healthprobe
  solutions/audio_similarity_search/quick_deploy/audiosearch-docker-compose.yaml
  solutions/audio_similarity_search/quick_deploy/client/Dockerfile
Labels: size/XS

#995 fix issue with small audio files in audio similarity search
  solutions/audio_similarity_search/quick_deploy/server/src/operations/load.py
Labels: size/XS

#997 fix mysql data persisted in container issue in audio similarity
  solutions/audio_similarity_search/quick_deploy/audiosearch-docker-compose.yaml
Labels: size/XS

#1003 pad audio to one second so even short sounds will be indexed in audio similarity search data import
  solutions/audio_similarity_search/quick_deploy/server/src/encode.py
Labels: size/XS, audio_similarity_search/quick_deploy

#1001 add support for multiple audio file formats
  solutions/audio_similarity_search/quick_deploy/server/Dockerfile
  solutions/audio_similarity_search/quick_deploy/server/src/operations/load.py
Labels: size/S, audio_similarity_search/quick_deploy

#1009 Update Milvus Python SDK to preGA
  benchmark_test/scripts/requirements.txt
  solutions/audio_similarity_search/quick_deploy/server/requirements.txt
  solutions/audio_similarity_search/requirements.txt
  solutions/dna_sequence_classification/quick_deploy/server/requirements.txt
  solutions/dna_sequence_classification/requirements.txt
  solutions/molecular_similarity_search/quick_deploy/server/requirements.txt
  solutions/question_answering_system/quick_deploy/server/requirements.txt
  solutions/reverse_image_search/object_detection/server/requirements.txt
  solutions/reverse_image_search/quick_deploy/server/requirements.txt
  solutions/text_search_engine/quick_deploy/server/requirements.txt
  solutions/text_search_engine/requirements.txt
  solutions/video_similarity_search/quick_deploy/server/requirements.txt
Labels: size/M

#1015 Update Milvus Python SDK to 2.0
  benchmark_test/scripts/requirements.txt
  solutions/audio_similarity_search/quick_deploy/server/requirements.txt
  solutions/audio_similarity_search/requirements.txt
  solutions/dna_sequence_classification/quick_deploy/server/requirements.txt
  solutions/dna_sequence_classification/requirements.txt
  solutions/molecular_similarity_search/quick_deploy/server/requirements.txt
  solutions/question_answering_system/quick_deploy/server/requirements.txt
  solutions/reverse_image_search/object_detection/server/requirements.txt
  solutions/reverse_image_search/quick_deploy/server/requirements.txt
  solutions/text_search_engine/quick_deploy/server/requirements.txt
  solutions/text_search_engine/requirements.txt
  solutions/video_similarity_search/quick_deploy/server/requirements.txt
Labels: size/S
