Repository milvus-io/bootcamp, pull requests merged in 2023-09, with the labels that each got.

#1169 add biological multifactor authenticate
  solutions/image/biological_multifactor_authentication/README.md
  solutions/image/biological_multifactor_authentication/server/Dockerfile
  solutions/image/biological_multifactor_authentication/server/requirements.txt
  solutions/image/biological_multifactor_authentication/server/src/app.py
  solutions/image/biological_multifactor_authentication/server/src/authentication_milvus.py
  solutions/image/biological_multifactor_authentication/server/src/models/ResNet.py
  solutions/image/biological_multifactor_authentication/server/src/models/ResNet_aug.py
  solutions/image/biological_multifactor_authentication/server/src/models/fusion.py
  solutions/image/biological_multifactor_authentication/server/src/models/pooling_layers.py
  solutions/image/biological_multifactor_authentication/server/src/static/css/bootstrap.min.css
  solutions/image/biological_multifactor_authentication/server/src/static/css/index.css
  solutions/image/biological_multifactor_authentication/server/src/static/css/style.default.css
  solutions/image/biological_multifactor_authentication/server/src/static/js/bootstrap.min.js
  solutions/image/biological_multifactor_authentication/server/src/static/js/front.js
  solutions/image/biological_multifactor_authentication/server/src/static/js/index.js
  solutions/image/biological_multifactor_authentication/server/src/static/js/jquery-1.11.0.js
  solutions/image/biological_multifactor_authentication/server/src/static/js/jquery.min.js
  solutions/image/biological_multifactor_authentication/server/src/templates/index.html
  solutions/image/biological_multifactor_authentication/server/src/voice_embedding.py
Labels: size/XXL

#1165 Add devcontainer for easy demo/dev of notebooks via Codespaces
  .devcontainer/devcontainer.json
  .devcontainer/requirements.txt
Labels: size/M

#1164 Update q/a system server requirements.txt
  solutions/nlp/question_answering_system/server/requirements.txt
Labels: size/XS
