Repository milvus-io/bootcamp, pull requests merged in 2023-05, with the labels that each got.

#1138 changing text example to a better one
  notebooks/text/movie_plot_semantic_search.ipynb
  notebooks/text/white_house_speeches.ipynb
Labels: size/XL

#1137 qa: fix load data with no index error
  solutions/nlp/question_answering_system/quick_deploy/server/src/milvus_helpers.py
  solutions/nlp/question_answering_system/quick_deploy/server/src/operations/load.py
Labels: size/XS

#1135 qa: update source code deploy
  solutions/nlp/question_answering_system/quick_deploy/README.md
Labels: size/XS

#1141 Improve reverse_ image_ search performance
  solutions/image/reverse_image_search/quick_deploy/server/requirements.txt
  solutions/image/reverse_image_search/quick_deploy/server/src/encode.py
Labels: size/S

#1144 Audio similarity search updates
  solutions/audio/audio_similarity_search/audio_similarity_search.ipynb
  solutions/audio/audio_similarity_search/requirements.txt
Labels: size/L
