Repository milvus-io/bootcamp, pull requests merged in 2023-12, with the labels that each got.

#1213 evaluate fiqa customized RAG
  evaluation/evaluate_fiqa_customized_RAG.ipynb
Labels: size/L

#1214 add readme and docs
  evaluation/README.md
  evaluation/evaluate_fiqa_customized_RAG.ipynb
  evaluation/evaluate_fiqa_openai.ipynb
Labels: size/L

#1215 fix topk, add comparision table
  evaluation/README.md
  evaluation/evaluate_fiqa_customized_RAG.ipynb
Labels: size/S

#1216 Add new Zilliz Pipelines demo, clean up old doc pages from data folder
  bootcamp/RAG/readthedocs_zilliz_langchain.ipynb
  bootcamp/RAG/rtdocs/pymilvus.readthedocs.io/en/1.0/_modules/index.html
  bootcamp/RAG/rtdocs/pymilvus.readthedocs.io/en/1.0/_modules/milvus/client/stub.html
  bootcamp/RAG/rtdocs/pymilvus.readthedocs.io/en/1.0/_modules/milvus/client/types.html
  bootcamp/RAG/rtdocs/pymilvus.readthedocs.io/en/1.0/about.html
  bootcamp/RAG/rtdocs/pymilvus.readthedocs.io/en/1.0/api.html
  bootcamp/RAG/rtdocs/pymilvus.readthedocs.io/en/1.0/changes.html
  bootcamp/RAG/rtdocs/pymilvus.readthedocs.io/en/1.0/contribute.html
  bootcamp/RAG/rtdocs/pymilvus.readthedocs.io/en/1.0/faq.html
  bootcamp/RAG/rtdocs/pymilvus.readthedocs.io/en/1.0/genindex.html
  bootcamp/RAG/rtdocs/pymilvus.readthedocs.io/en/1.0/index.html
  bootcamp/RAG/rtdocs/pymilvus.readthedocs.io/en/1.0/install.html
  bootcamp/RAG/rtdocs/pymilvus.readthedocs.io/en/1.0/param.html
  bootcamp/RAG/rtdocs/pymilvus.readthedocs.io/en/1.0/results.html
  bootcamp/RAG/rtdocs/pymilvus.readthedocs.io/en/1.0/search.html
  bootcamp/RAG/rtdocs/pymilvus.readthedocs.io/en/1.0/tutorial.html
  bootcamp/RAG/rtdocs/pymilvus.readthedocs.io/en/1.1/_modules/index.html
  bootcamp/RAG/rtdocs/pymilvus.readthedocs.io/en/1.1/_modules/milvus/client/stub.html
  bootcamp/RAG/rtdocs/pymilvus.readthedocs.io/en/1.1/_modules/milvus/client/types.html
  bootcamp/RAG/rtdocs/pymilvus.readthedocs.io/en/1.1/about.html
  bootcamp/RAG/rtdocs/pymilvus.readthedocs.io/en/1.1/api.html
  bootcamp/RAG/rtdocs/pymilvus.readthedocs.io/en/1.1/changes.html
  bootcamp/RAG/rtdocs/pymilvus.readthedocs.io/en/1.1/contribute.html
  bootcamp/RAG/rtdocs/pymilvus.readthedocs.io/en/1.1/faq.html
  bootcamp/RAG/rtdocs/pymilvus.readthedocs.io/en/1.1/genindex.html
  bootcamp/RAG/rtdocs/pymilvus.readthedocs.io/en/1.1/index.html
  bootcamp/RAG/rtdocs/pymilvus.readthedocs.io/en/1.1/install.html
  bootcamp/RAG/rtdocs/pymilvus.readthedocs.io/en/1.1/param.html
  bootcamp/RAG/rtdocs/pymilvus.readthedocs.io/en/1.1/results.html
  bootcamp/RAG/rtdocs/pymilvus.readthedocs.io/en/1.1/search.html
  bootcamp/RAG/rtdocs/pymilvus.readthedocs.io/en/1.1/tutorial.html
  bootcamp/RAG/rtdocs/pymilvus.readthedocs.io/en/latest/_modules/index.html
  bootcamp/RAG/rtdocs/pymilvus.readthedocs.io/en/latest/about.html
  bootcamp/RAG/rtdocs/pymilvus.readthedocs.io/en/latest/changes.html
  bootcamp/RAG/rtdocs/pymilvus.readthedocs.io/en/latest/contribute.html
  bootcamp/RAG/rtdocs/pymilvus.readthedocs.io/en/latest/faq.html
  bootcamp/RAG/rtdocs/pymilvus.readthedocs.io/en/latest/genindex.html
  bootcamp/RAG/rtdocs/pymilvus.readthedocs.io/en/latest/index.html
Labels: size/XXL

#1219 Add text in notebook and image for Zilliz pipelines
  bootcamp/RAG/readthedocs_zilliz_langchain.ipynb
  images/zilliz_pipeline_s3.png
Labels: size/S

#1224 Update notebooks move functions to utils.py
  bootcamp/RAG/readthedocs_zilliz_langchain.ipynb
  bootcamp/Retrieval/imdb_milvus_client.ipynb
Labels: size/XL

#1227 refine comment words
  bootcamp/RAG/zilliz_pipeline_rag.ipynb
Labels: size/XS

#1228 add screenshot for config
  bootcamp/RAG/zilliz_pipeline_rag.ipynb
  images/zilliz_api_key_cluster_id.jpeg
Labels: size/S

#1229 Update zilliz_pipeline_rag.ipynb
  bootcamp/RAG/zilliz_pipeline_rag.ipynb
Labels: size/M

#1231 advanced zilliz pipeline rag
  bootcamp/RAG/pipeline_utils.py
  bootcamp/RAG/zilliz_pipeline_rag_advanced.ipynb
Labels: size/XL

#1232 Update title and summary of bootcamp/RAG/zilliz_pipeline_rag_advanced.ipynb
  bootcamp/RAG/zilliz_pipeline_rag_advanced.ipynb
Labels: size/M
