Repository milvus-io/bootcamp, pull requests merged in 2023-10, with the labels that each got.

#1172 Add simple text vector search IMDB no-schema Milvus Client
  .env
  notebooks/text/imdb_search_milvus_client.ipynb
  notebooks/text/imdb_utilities.py
Labels: size/XXL

#1173 Add TODO coding exercises
  notebooks/text/imdb_search_milvus_client.ipynb
Labels: size/L

#1175 Add langchain rag example
  images/rag_image.png
  notebooks/llms/langchain/readthedocs_rag_milvus_client.ipynb
Labels: size/XL

#1174 New recommender system
  solutions/nlp/recommender_system/cluster_info.png
  solutions/nlp/recommender_system/recommender_system.ipynb
Labels: size/XL
