Repository milvus-io/bootcamp, pull requests merged in 2023-11, with the labels that each got.

#1184 Add notebook: llama_index OpenaiAssistantAgent with Milvus
  notebooks/llms/llamaindex/llamaindex_agent_openai_assistant_with_milvus.ipynb
Labels: size/L

#1185 Update llama_index notebook
  notebooks/llms/llamaindex/llamaindex_agent_openai_assistant_with_milvus.ipynb
Labels: size/L

#1186 Update sample data, update notebook explanations
  notebooks/text/data/movie_data.csv
  notebooks/text/imdb_search_milvus_client.ipynb
Labels: size/XL

#1187 Update simple OSS RAG demo
  notebooks/llms/langchain/readthedocs_rag_milvus_client.ipynb
  notebooks/text/imdb_search_milvus_client.ipynb
Labels: size/XL

#1188 Update simple text retrieval demo
  notebooks/text/imdb_search_milvus_client.ipynb
Labels: size/S

#1190 Add Zilliz free tier example
  notebooks/llms/langchain/readthedocs_rag_zilliz.ipynb
Labels: size/XL

#1191 Add Zilliz free tier example
  notebooks/llms/langchain/readthedocs_rag_zilliz.ipynb
Labels: size/L

#1192 Add Zilliz free tier example
  notebooks/llms/langchain/readthedocs_rag_zilliz.ipynb
Labels: size/L

#1194 Add Zilliz free tier simple OSS RAG example
  notebooks/llms/langchain/readthedocs_rag_milvus_client.ipynb
  notebooks/llms/langchain/readthedocs_rag_zilliz.ipynb
Labels: size/XL

#1195 Add Zilliz free tier simple OSS RAG example
  notebooks/llms/langchain/readthedocs_rag_zilliz.ipynb
Labels: size/XS

#1200 Add instructions how to add api token to connect zilliz
  images/zilliz_cluster_uri_token.png
  notebooks/milvus_connect.ipynb
Labels: size/M

#1202 Cleanup notebooks
  images/db_insert.png
  notebooks/llms/langchain/readthedocs_rag_zilliz.ipynb
  notebooks/text/imdb_search_milvus_client.ipynb
Labels: size/L

#1204 Add readme for bootcamp tutorials
  README.md
  bootcamp/tutorials_README.md
Labels: size/S
