Repository milvus-io/bootcamp, pull requests merged in 2023-06, with the labels that each got.

#1148 Fix opencv issue
  solutions/video/video_similarity_search/quick_deploy/server/src/frame_extract.py
  solutions/video/video_similarity_search/requirements.txt
Labels: size/XS

#1150 adding 1 langchain and 1 llamaindex llm example notebooks
  notebooks/llms/langchain/lc_vectorstore_conv_mem.ipynb
  notebooks/llms/llamaindex/multi_doc_qa.ipynb
Labels: size/XL

#1151 Update pymilvus version
  solutions/nlp/text_search_engine/requirements.txt
Labels: size/XS

#1155 Update recomender system
  solutions/nlp/recommender_system/recommender_system.ipynb
Labels: size/XL

#1156 Update README
  README.md
  benchmark_test/README.md
  benchmark_test/concurrent-test/multi_process_insert.py
  benchmark_test/concurrent-test/multi_process_search.py
  benchmark_test/lab1_sift1b_1m.md
  benchmark_test/lab2_sift1b_100m.md
  benchmark_test/scripts/README.md
  benchmark_test/scripts/config.py
  benchmark_test/scripts/load.py
  benchmark_test/scripts/logs.py
  benchmark_test/scripts/main.py
  benchmark_test/scripts/milvus_helpers.py
  benchmark_test/scripts/performance_test.py
  benchmark_test/scripts/recall_test.py
  benchmark_test/scripts/requirements.txt
  benchmark_test/scripts/test_main.py
  etc/README.md
  etc/deploy_milvus_on_kubesphere.md
  etc/onnx_and_milvus/milvus_with_different_models.ipynb
  etc/onnx_and_milvus/pic/example.jpg
  etc/onnx_and_milvus/requirements.txt
  etc/pic/image-20220318143334767.png
  etc/pic/image-20220318143931895.png
  etc/pic/image-20220318172633333.png
  etc/pic/image-20220318172745769.png
  etc/pic/image-20220318172913153.png
  etc/pic/image-20220318175622525.png
Labels: size/XXL

#1157 Update image search with latest Milvus and Towhee
  README.md
  solutions/image/reverse_image_search/README.md
  solutions/image/reverse_image_search/docker-compose.yaml
  solutions/image/reverse_image_search/pic/demo.jpg
  solutions/image/reverse_image_search/pic/workflow.png
  solutions/image/reverse_image_search/server/Dockerfile
  solutions/image/reverse_image_search/server/requirements.txt
  solutions/image/reverse_image_search/server/src/encode.py
  solutions/image/reverse_image_search/server/src/logs.py
  solutions/image/reverse_image_search/server/src/main.py
  solutions/image/reverse_image_search/server/src/milvus_helpers.py
  solutions/image/reverse_image_search/server/src/operations/__init__.py
  solutions/image/reverse_image_search/server/src/operations/count.py
  solutions/image/reverse_image_search/server/src/operations/drop.py
  solutions/image/reverse_image_search/server/src/operations/load.py
  solutions/image/reverse_image_search/server/src/operations/search.py
  solutions/image/reverse_image_search/server/src/operations/upload.py
Labels: size/L

#1159 Update issue template
  .github/ISSUE_TEMPLATE/--bug-report.yaml
  .github/ISSUE_TEMPLATE/--feature-request.yaml
Labels: size/XS

#1160 Update QA chatbot
  solutions/nlp/question_answering_system/README.md
  solutions/nlp/question_answering_system/server/Dockerfile
  solutions/nlp/question_answering_system/server/requirements.txt
  solutions/nlp/question_answering_system/server/src/QA_data/example_data.csv
  solutions/nlp/question_answering_system/server/src/__init__.py
  solutions/nlp/question_answering_system/server/src/config.py
  solutions/nlp/question_answering_system/server/src/encode.py
  solutions/nlp/question_answering_system/server/src/main.py
  solutions/nlp/question_answering_system/server/src/milvus_helpers.py
  solutions/nlp/question_answering_system/server/src/operations/__init__.py
  solutions/nlp/question_answering_system/server/src/operations/count.py
  solutions/nlp/question_answering_system/server/src/operations/drop.py
  solutions/nlp/question_answering_system/server/src/operations/load.py
  solutions/nlp/question_answering_system/server/src/operations/search.py
Labels: size/L

#1161 Update milvus_helpers.py
  solutions/image/reverse_image_search/server/src/milvus_helpers.py
Labels: size/XS
