Repository milvus-io/bootcamp, pull requests merged in 2024-02, with the labels that each got.

#1257 Update RAG langchain notebook using DirectoryLoader instead of ReadTh…
  bootcamp/RAG/readthedocs_zilliz_langchain.ipynb
  bootcamp/RAG/rtdocs/pymilvus.readthedocs.io/en/latest/stub.html
  bootcamp/RAG/rtdocs/pymilvus.readthedocs.io/en/latest/types.html
  bootcamp/milvus_utilities.py
Labels: size/L

#1261 add m3 embedding milvus retrieval
  bootcamp/Integration/bge_m3_embedding.ipynb
  bootcamp/Integration/docs/m3_paper.txt
  images/bge_m3.png
Labels: size/XL

#1262 Update description
  bootcamp/Integration/bge_m3_embedding.ipynb
Labels: size/M, lgtm

#1265 blog ZCP new embeddings notebook
  bootcamp/RAG/zilliz_cloud_emb3.ipynb
Labels: size/XL

#1266 blog ZCP new embeddings notebook
  bootcamp/RAG/zilliz_cloud_emb3.ipynb
Labels: size/S
