Repository milvus-io/bootcamp, pull requests merged in 2024-08, with the labels that each got.

#1403 Christy
  bootcamp/workshops/dbta_may_2024/1. RAG_basic.ipynb
Labels: size/L

#1404 Update tutorials
  bootcamp/tutorials/quickstart/build_RAG_with_milvus.ipynb
  bootcamp/tutorials/quickstart/cir_with_milvus.ipynb
  bootcamp/tutorials/quickstart/hybrid_search_with_milvus.ipynb
  bootcamp/tutorials/quickstart/image_search_with_milvus.ipynb
  bootcamp/tutorials/quickstart/multimodal_rag_with_milvus.ipynb
Labels: size/L

#1406 Add airbyte integration doc
  bootcamp/tutorials/integration/airbyte_with_milvus.md
  images/airbyte_with_milvus_1.png
  images/airbyte_with_milvus_2.png
  images/airbyte_with_milvus_3.png
  images/airbyte_with_milvus_4.png
  images/airbyte_with_milvus_5.png
  images/airbyte_with_milvus_6.png
Labels: size/L

#1401 [llama-agents] Add an example w/ llama-agents and Milvus
  bootcamp/tutorials/integration/llama_agents_metadata.ipynb
Labels: size/XL

#1407 Neo4j graphrag ingest notebook added
  bootcamp/RAG/advanced_rag/langchain-graphrag-ingest-local.ipynb
Labels: size/L

#1408 Update hybrid_search_with_milvus.ipynb to use csr index.
  bootcamp/tutorials/quickstart/hybrid_search_with_milvus.ipynb
Labels: size/XS

#1409 GraphRAG retrieval example added
  bootcamp/RAG/advanced_rag/langgraph-graphrag-agent-local.ipynb
Labels: size/XL
