Repository milvus-io/bootcamp, pull requests merged in 2024-09, with the labels that each got.

#1413 evaluation_with_deepeval notebook done
  bootcamp/tutorials/integration/evaluation_with_deepeval.ipynb
Labels: size/XL

#1415 Hide log, balck format checked
  bootcamp/tutorials/integration/evaluation_with_deepeval.ipynb
Labels: size/L

#1417 Update sparse_dense_embeddings_tutorial.ipynb
  bootcamp/RAG/sparse_dense_embeddings_tutorial.ipynb
Labels: size/XS

#1416 Add folder for milvus usages
  bootcamp/tutorials/milvus_usages/README.md
Labels: size/XS

#1418 graph rag with milvus
  bootcamp/tutorials/integration/graph_rag_with_milvus.ipynb
  images/graph_rag_with_milvus_1.png
  images/graph_rag_with_milvus_2.png
Labels: size/XL

#1419 Improve GraphRAG w/ Neo4j
  bootcamp/RAG/advanced_rag/langgraph-graphrag-agent-local.ipynb
Labels: size/XXL

#1421 Cleanup Milvus & Neo4j notebook
  bootcamp/RAG/advanced_rag/langgraph-graphrag-agent-local.ipynb
Labels: size/XXL

#1423 dify integration
  bootcamp/tutorials/integration/dify_with_milvus.md
Labels: size/M

#1424 Update README.md
  bootcamp/tutorials/quickstart/apps/rag_search_with_milvus/README.md
Labels: size/S

#1425 add tracing panel image
  bootcamp/tutorials/integration/evaluation_with_phoenix.ipynb
  images/phoenix01.png
Labels: size/M

#1426 apify
  bootcamp/tutorials/integration/apify_milvus_rag.ipynb
Labels: size/L

#1427 Add contexual retrieval for milvus.
  bootcamp/tutorials/quickstart/contextual_retrieval_with_milvus.ipynb
  images/contextual_retrieval_with_milvus.png
Labels: size/XL

#1429 repair and more badges
  bootcamp/tutorials/integration/evaluation_with_deepeval.ipynb
  bootcamp/tutorials/integration/evaluation_with_phoenix.ipynb
  bootcamp/tutorials/integration/evaluation_with_ragas.ipynb
  bootcamp/tutorials/integration/milvus_and_DSPy.ipynb
  bootcamp/tutorials/integration/milvus_with_Jina.ipynb
  bootcamp/tutorials/integration/qa_with_milvus_and_hf.ipynb
  bootcamp/tutorials/integration/rag_with_milvus_and_bentoml.ipynb
  bootcamp/tutorials/integration/rag_with_milvus_and_camel.ipynb
  bootcamp/tutorials/integration/rag_with_milvus_and_haystack.ipynb
  bootcamp/tutorials/integration/rag_with_milvus_and_langchain.ipynb
  bootcamp/tutorials/integration/rag_with_milvus_and_llamaindex.ipynb
  bootcamp/tutorials/integration/semantic_search_with_milvus_and_openai.ipynb
  bootcamp/tutorials/integration/semantic_search_with_milvus_and_voyageai.ipynb
  bootcamp/tutorials/integration/vanna_write_sql.ipynb
  bootcamp/tutorials/quickstart/build_RAG_with_milvus.ipynb
  bootcamp/tutorials/quickstart/graph_rag_with_milvus.ipynb
  bootcamp/tutorials/quickstart/hybrid_search_with_milvus.ipynb
  bootcamp/tutorials/quickstart/image_search_with_milvus.ipynb
  bootcamp/tutorials/quickstart/multimodal_rag_with_milvus.ipynb
  bootcamp/tutorials/quickstart/quickstart.ipynb
Labels: size/M

#1430 Fix wrong image url in contextual_retrieval_with_milvus notebook.
  bootcamp/tutorials/quickstart/contextual_retrieval_with_milvus.ipynb
Labels: size/S
