Repository milvus-io/bootcamp, pull requests merged in 2024-04, with the labels that each got.

#1282 Add ray data notebook
  bootcamp/Integration/data/kaggle_imdb_small.parquet
  bootcamp/Integration/ray_data_demo.py
Labels: size/L

#1283 Add notebook about rerankers in model lib.
  bootcamp/model/reranker.ipynb
Labels: size/L

#1284 Add Ray Data notebook for blog, update connections Milvus 2.4
  bootcamp/Integration/data/kaggle_imdb_small.parquet
  bootcamp/Integration/ray_data_demo.py
  bootcamp/RAG/readthedocs_zilliz_langchain.ipynb
  bootcamp/milvus_connect.ipynb
Labels: size/XL

#1287 Add Ray Data notebook for blog, update connections Milvus 2.4
  bootcamp/Integration/ray_data_demo.py
  bootcamp/milvus_connect.ipynb
Labels: size/L

#1288 Update for v2.4 readme, milvus_connect
  bootcamp/README.md
  bootcamp/milvus_connect.ipynb
Labels: size/S

#1289 Add workshop demo
  bootcamp/workshops/sfbayacm_april_24_2024.ipynb
Labels: size/XXL

#1291 Add workshop demo
  bootcamp/Evaluation/data/ground_truth_answers.csv
  bootcamp/Evaluation/data/ground_truth_answers.numbers
  bootcamp/Integration/eval_ragas.py
  bootcamp/Integration/ray_data_demo.py
  bootcamp/milvus_connect.ipynb
  bootcamp/workshops/sfbayacm_april_24_2024.ipynb
Labels: size/XXL

#1296 Add workshop demo
  bootcamp/Evaluation/data/ground_truth_answers.csv
  bootcamp/Evaluation/data/ground_truth_answers.numbers
  bootcamp/Evaluation/eval_ragas.ipynb
  bootcamp/Integration/eval_ragas.py
  bootcamp/workshops/sfbayacm_april_24_2024.ipynb
  images/anthropic_claude3.png
  images/db_insert_sparse_dense.png
Labels: size/XXL

#1297 add aws bedrock_langchain_zilliz_rag.ipynb
  bootcamp/RAG/bedrock_langchain_zilliz_rag.ipynb
  images/zilliz_uri_and_key.png
Labels: size/L
