Repository milvus-io/bootcamp, pull requests merged in 2024-12, with the labels that each got.

#1470 Update use_ColPali_with_milvus.ipynb
  bootcamp/tutorials/quickstart/use_ColPali_with_milvus.ipynb
Labels: size/XS

#1471 build_RAG_with_milvus_and_cognee
  bootcamp/tutorials/integration/build_RAG_with_milvus_and_cognee.ipynb
Labels: size/L

#1472 optimize cognee
  bootcamp/tutorials/integration/build_RAG_with_milvus_and_cognee.ipynb
Labels: size/L

#1473 Update full text search notebook.
  bootcamp/tutorials/quickstart/full_text_search_with_milvus.ipynb
Labels: size/XL

#1475 fix dynamiq url
  bootcamp/tutorials/integration/milvus_rag_with_dynamiq.ipynb
Labels: size/XS

#1478 advanced_rag
  bootcamp/tutorials/quickstart/how_to_enhance_your_rag.md
  images/advanced_rag/adjust_order.png
  images/advanced_rag/compress_prompt.png
  images/advanced_rag/hierarchical_index.png
  images/advanced_rag/hybrid_and_rerank.png
  images/advanced_rag/hyde.png
  images/advanced_rag/hypothetical_question.png
  images/advanced_rag/merge_chunks.png
  images/advanced_rag/metadata_filtering.png
  images/advanced_rag/query_routing.png
  images/advanced_rag/query_routing_with_sub_query.png
  images/advanced_rag/self_reflection.png
  images/advanced_rag/sentence_window.png
  images/advanced_rag/stepback.png
  images/advanced_rag/sub_query.png
  images/advanced_rag/vanilla_rag.png
Labels: size/L

#1479 advanced_rag README
  bootcamp/RAG/advanced_rag/README.md
Labels: size/L
