Repository milvus-io/bootcamp, pull requests merged in 2024-05, with the labels that each got.

#1298 Add workshop demo
  bootcamp/Integration/eval_ragas.py
  bootcamp/RAG/readthedocs_zilliz_langchain.ipynb
  bootcamp/RAG/rtdocs/pymilvus.readthedocs.io/en/latest/api.html
  bootcamp/RAG/rtdocs/pymilvus.readthedocs.io/en/latest/install.html
  bootcamp/RAG/rtdocs/pymilvus.readthedocs.io/en/latest/param.html
  bootcamp/RAG/rtdocs/pymilvus.readthedocs.io/en/latest/results.html
  bootcamp/RAG/rtdocs/pymilvus.readthedocs.io/en/latest/search.html
  bootcamp/RAG/rtdocs/pymilvus.readthedocs.io/en/latest/stub.html
  bootcamp/RAG/rtdocs/pymilvus.readthedocs.io/en/latest/tutorial.html
  bootcamp/RAG/rtdocs/pymilvus.readthedocs.io/en/latest/types.html
  bootcamp/workshops/sfbayacm_april_24_2024.ipynb
Labels: size/XXL

#1300 Christy demo
  bootcamp/RAG/readthedocs_zilliz_langchain.ipynb
  bootcamp/workshops/sfbayacm_april_24_2024.ipynb
  images/mistral_mixtral.png
Labels: size/L

#1301 Add sample data for demos
  bootcamp/Evaluation/data/ground_truth_answers.csv
  bootcamp/RAG/rtdocs/.html
  bootcamp/RAG/rtdocs/architecture_overview.html
  bootcamp/RAG/rtdocs/aws.html
  bootcamp/RAG/rtdocs/configure-docker.html
  bootcamp/RAG/rtdocs/deploy_s3.html
  bootcamp/RAG/rtdocs/embeddings.html
  bootcamp/RAG/rtdocs/get-and-scalar-query.html
  bootcamp/RAG/rtdocs/glossary.html
  bootcamp/RAG/rtdocs/gpu_index.html
  bootcamp/RAG/rtdocs/index-vector-fields.html
  bootcamp/RAG/rtdocs/index.html
  bootcamp/RAG/rtdocs/insert-update-delete.html
  bootcamp/RAG/rtdocs/install_standalone-docker.html
  bootcamp/RAG/rtdocs/manage-collections.html
  bootcamp/RAG/rtdocs/metric.html
  bootcamp/RAG/rtdocs/milvus-cdc-overview.html
  bootcamp/RAG/rtdocs/monitor_overview.html
  bootcamp/RAG/rtdocs/multi-vector-search.html
  bootcamp/RAG/rtdocs/quickstart.html
  bootcamp/RAG/rtdocs/rbac.html
  bootcamp/RAG/rtdocs/scaleout.html
  bootcamp/RAG/rtdocs/single-vector-search.html
  bootcamp/RAG/rtdocs/system_configuration.html
Labels: size/XXL

#1303 Add workshop notebooks
  bootcamp/workshops/dbta_may_2024/1. RAG_basic.ipynb
Labels: size/XL

#1304 Update workshop notebooks
  bootcamp/workshops/dbta_may_2024/1. RAG_basic.ipynb
  bootcamp/workshops/sfbayacm_april_24_2024.ipynb
Labels: size/XL

#1305 Update pymilvus version and docker container version
  bootcamp/workshops/sfbayacm_april_24_2024.ipynb
Labels: size/S

#1306 fix prompt
  bootcamp/RAG/bedrock_langchain_zilliz_rag.ipynb
Labels: size/XS

#1307 Add Zilliz Cloud Pipeline Text demo
  bootcamp/RAG/zilliz_pipeline_rag_text.ipynb
  images/rag_and_pipeline_text.png
Labels: size/XL, lgtm

#1295 Add Bento demo
  bootcamp/RAG/city_data/Boston.txt
  bootcamp/RAG/city_data/Cambridge, Massachusetts.txt
  bootcamp/RAG/city_data/Chicago.txt
  bootcamp/RAG/city_data/Houston.txt
  bootcamp/RAG/city_data/San Francisco.txt
  bootcamp/RAG/city_data/Seattle.txt
  bootcamp/RAG/city_data/Toronto.txt
  bootcamp/RAG/city_data/Washington, D.C..txt
  bootcamp/RAG/zilliz_bento_RAG.ipynb
  images/bento_zilliz_rag_llm.jpeg
  images/bento_zilliz_rag_p1.png
  images/bento_zilliz_rag_p2.png
Labels: size/XXL

#1308 add build_RAG_with_milvus.ipynb
  bootcamp/milvus-lite/build_RAG_with_milvus.ipynb
Labels: size/L

#1309 refine build_RAG_with_milvus.ipynb colab
  bootcamp/milvus-lite/build_RAG_with_milvus.ipynb
Labels: size/XS

#1310 Add LlamaIndex demo for milvus-lite
  bootcamp/milvus-lite/rag_with_milvus_and_llamaindex.ipynb
Labels: size/L

#1312 change tutorial dir
  bootcamp/tutorials/integration/rag_with_milvus_and_langchain.ipynb
  bootcamp/tutorials/integration/rag_with_milvus_and_llamaindex.ipynb
  bootcamp/tutorials/quickstart/build_RAG_with_milvus.ipynb
Labels: size/XS

#1313 add guide about using env variables in colab
  bootcamp/tutorials/integration/rag_with_milvus_and_langchain.ipynb
  bootcamp/tutorials/quickstart/build_RAG_with_milvus.ipynb
Labels: size/XS

#1314 change guide of init env variable
  bootcamp/tutorials/integration/rag_with_milvus_and_langchain.ipynb
  bootcamp/tutorials/quickstart/build_RAG_with_milvus.ipynb
Labels: size/M

#1315 Add notebook of image search.
  bootcamp/tutorials/quickstart/image_search_with_milvus.ipynb
Labels: size/L

#1316 Update image_search_with_milvus.ipynb
  bootcamp/tutorials/quickstart/image_search_with_milvus.ipynb
Labels: size/XS

#1317 Modify the typo in image_search_with_milvus.ipynb.
  bootcamp/tutorials/quickstart/image_search_with_milvus.ipynb
Labels: size/XS

#1318 Add instruction to restart runtime after pip install
  bootcamp/tutorials/integration/rag_with_milvus_and_llamaindex.ipynb
Labels: size/S

#1320 refine the use cases
  bootcamp/tutorials/integration/rag_with_milvus_and_haystack.ipynb
  bootcamp/tutorials/integration/rag_with_milvus_and_langchain.ipynb
  bootcamp/tutorials/quickstart/build_RAG_with_milvus.ipynb
Labels: size/L

#1321 add evaluation_with_ragas.ipynb
  bootcamp/tutorials/integration/evaluation_with_ragas.ipynb
  bootcamp/tutorials/quickstart/build_RAG_with_milvus.ipynb
Labels: size/XL

#1322 refine doc
  bootcamp/tutorials/integration/evaluation_with_ragas.ipynb
  bootcamp/tutorials/integration/rag_with_milvus_and_haystack.ipynb
Labels: size/S

#1324 Update image notebook.
  bootcamp/tutorials/quickstart/image_search_with_milvus.ipynb
Labels: size/L

#1327 notebooks cleanup
  bootcamp/RAG/readthedocs_zilliz_langchain.ipynb
  bootcamp/workshops/dbta_may_2024/1. RAG_basic.ipynb
Labels: size/XXL

#1331 Advanced rag
  bootcamp/RAG/advanced_rag/hybrid_and_rerank_with_langchain.ipynb
  bootcamp/RAG/advanced_rag/hyde_with_langchain.ipynb
  bootcamp/RAG/advanced_rag/imgs/colab_api_key1.png
  bootcamp/RAG/advanced_rag/imgs/colab_api_key2.png
  bootcamp/RAG/advanced_rag/imgs/hybrid_and_rerank.png
  bootcamp/RAG/advanced_rag/imgs/hybrid_and_rerank_res1.png
  bootcamp/RAG/advanced_rag/imgs/hybrid_and_rerank_res2.png
  bootcamp/RAG/advanced_rag/imgs/hyde.png
  bootcamp/RAG/advanced_rag/imgs/hyde_res1.png
  bootcamp/RAG/advanced_rag/imgs/hyde_res2.png
  bootcamp/RAG/advanced_rag/imgs/query_routing.png
  bootcamp/RAG/advanced_rag/imgs/sentence_window.png
  bootcamp/RAG/advanced_rag/imgs/sub_query.png
  bootcamp/RAG/advanced_rag/query_routing_with_langchain.ipynb
  bootcamp/RAG/advanced_rag/rag_utils/__init__.py
  bootcamp/RAG/advanced_rag/rag_utils/hybrid_and_rerank.py
  bootcamp/RAG/advanced_rag/rag_utils/hyde.py
  bootcamp/RAG/advanced_rag/rag_utils/route.py
  bootcamp/RAG/advanced_rag/rag_utils/sentence_window.py
  bootcamp/RAG/advanced_rag/rag_utils/sub_query.py
  bootcamp/RAG/advanced_rag/rag_utils/vanilla.py
  bootcamp/RAG/advanced_rag/sentence_window_with_langchain.ipynb
  bootcamp/RAG/advanced_rag/sub_query_with_langchain.ipynb
  bootcamp/RAG/advanced_rag/vanilla_rag_with_langchain.ipynb
Labels: size/XXL

#1332 memgpt
  bootcamp/tutorials/integration/memgpt_with_milvus.md
Labels: size/L

#1334 Update notebooks to use Milvus Lite
  bootcamp/workshops/dbta_may_2024/1. RAG_basic.ipynb
Labels: size/L

#1336 Christy demo
  bootcamp/Evaluation/data/ground_truth_answers.csv
  bootcamp/workshops/dbta_may_2024/1. RAG_basic.ipynb
Labels: size/L

#1337 Add tutorial for qa with milvus & hf
  bootcamp/tutorials/integration/qa_with_milvus_and_hf.ipynb
Labels: size/XL

#1338 black reformat
  .github/workflows/black.yml
  bootcamp/tutorials/integration/evaluation_with_ragas.ipynb
  bootcamp/tutorials/integration/qa_with_milvus_and_hf.ipynb
  bootcamp/tutorials/integration/rag_with_milvus_and_haystack.ipynb
  bootcamp/tutorials/integration/rag_with_milvus_and_langchain.ipynb
  bootcamp/tutorials/integration/rag_with_milvus_and_llamaindex.ipynb
  bootcamp/tutorials/quickstart/build_RAG_with_milvus.ipynb
  bootcamp/tutorials/quickstart/image_search_with_milvus.ipynb
Labels: size/L

#1339 add colab comment
  bootcamp/tutorials/integration/qa_with_milvus_and_hf.ipynb
  bootcamp/tutorials/integration/rag_with_milvus_and_langchain.ipynb
  bootcamp/tutorials/integration/rag_with_milvus_and_llamaindex.ipynb
  bootcamp/tutorials/quickstart/build_RAG_with_milvus.ipynb
  bootcamp/tutorials/quickstart/image_search_with_milvus.ipynb
Labels: size/M

#1340 remove hf output
  bootcamp/tutorials/integration/qa_with_milvus_and_hf.ipynb
Labels: size/L

#1341 adapt with last released langchain_milvus package
  bootcamp/RAG/advanced_rag/hybrid_and_rerank_with_langchain.ipynb
  bootcamp/RAG/advanced_rag/hyde_with_langchain.ipynb
  bootcamp/RAG/advanced_rag/query_routing_with_langchain.ipynb
  bootcamp/RAG/advanced_rag/sentence_window_with_langchain.ipynb
  bootcamp/RAG/advanced_rag/sub_query_with_langchain.ipynb
  bootcamp/RAG/advanced_rag/vanilla_rag_with_langchain.ipynb
Labels: size/L

#1343 update colab link
  bootcamp/RAG/advanced_rag/hybrid_and_rerank_with_langchain.ipynb
  bootcamp/RAG/advanced_rag/hyde_with_langchain.ipynb
  bootcamp/RAG/advanced_rag/query_routing_with_langchain.ipynb
  bootcamp/RAG/advanced_rag/sentence_window_with_langchain.ipynb
  bootcamp/RAG/advanced_rag/sub_query_with_langchain.ipynb
  bootcamp/RAG/advanced_rag/vanilla_rag_with_langchain.ipynb
Labels: size/S

#1344 add advanced rag link
  bootcamp/tutorials/integration/rag_with_milvus_and_langchain.ipynb
Labels: size/S

#1328 Proof Read several Milvus Lite integrations and convert to notebook
  bootcamp/tutorials/integration/milvus_and_DSPy.ipynb
  bootcamp/tutorials/integration/milvus_with_Jina.ipynb
  bootcamp/tutorials/integration/rag_with_milvus_and_bentoml.ipynb
  bootcamp/tutorials/integration/semantic_search_with_milvus_and_openai.ipynb
  bootcamp/tutorials/integration/semantic_search_with_milvus_and_voyageai.ipynb
  bootcamp/tutorials/quickstart/quickstart.ipynb
  images/DSPy_milvus.png
Labels: size/XXL

#1345 Update integration notebook format and Add Jina Semantic Search
  bootcamp/tutorials/integration/milvus_and_DSPy.ipynb
  bootcamp/tutorials/integration/milvus_with_Jina.ipynb
  bootcamp/tutorials/integration/qa_with_milvus_and_hf.ipynb
  bootcamp/tutorials/integration/rag_with_milvus_and_llamaindex.ipynb
  bootcamp/tutorials/quickstart/image_search_with_milvus.ipynb
  bootcamp/tutorials/quickstart/quickstart.ipynb
Labels: size/L

#1346 Update format and add colab warning
  bootcamp/tutorials/integration/milvus_and_DSPy.ipynb
  bootcamp/tutorials/integration/milvus_with_Jina.ipynb
  bootcamp/tutorials/integration/rag_with_milvus_and_bentoml.ipynb
  bootcamp/tutorials/integration/semantic_search_with_milvus_and_openai.ipynb
  bootcamp/tutorials/integration/semantic_search_with_milvus_and_voyageai.ipynb
Labels: size/L
