Repository milvus-io/bootcamp, pull requests merged in 2024-03, with the labels that each got.

#1273 Try ragas eval
  bootcamp/Evaluation/eval_ragas.ipynb
  images/ragas_eval_image.png
Labels: size/XL

#1276 Add a notebook to introduce the embedding functions.
  bootcamp/model/embedding_functions.ipynb
Labels: size/XL

#1278 Add JSON Metadata filtering notebook
  bootcamp/Retrieval/data/tiny_parsed_data.json
  bootcamp/Retrieval/imdb_metadata_json.ipynb
Labels: size/XXL

#1279 Christy demo
  bootcamp/RAG/sparse_dense_embeddings_tutorial.ipynb
  bootcamp/Retrieval/imdb_metadata_json.ipynb
Labels: size/L

#1280 Add ray data notebook
  bootcamp/Integration/data/kaggle_imdb_small.parquet
  bootcamp/Integration/ray_data.ipynb
  bootcamp/Integration/ray_data_demo.py
  bootcamp/Retrieval/imdb_metadata_json.ipynb
Labels: size/XL

#1281 Add ray data notebook
  bootcamp/Integration/ray_data.ipynb
  bootcamp/Integration/ray_data_demo.py
Labels: size/XL
