Repository milvus-io/bootcamp, pull requests merged in 2024-10, with the labels that each got.

#1433 Fix Typo in readme file
  README.md
Labels: size/XS

#1431 langflow notebook v1
  bootcamp/tutorials/integration/rag_with_langflow.ipynb
  images/langflow_dashboard_new_project.png
  images/langflow_dashboard_start.png
  images/langflow_default_structure.png
  images/langflow_milvus_sidebar.png
  images/langflow_milvus_structure.png
  images/langflow_why_milvus.png
Labels: size/L

#1434 ARM integration
  bootcamp/tutorials/integration/build_rag_on_arm.md
Labels: size/L

#1435 badge
  bootcamp/tutorials/quickstart/contextual_retrieval_with_milvus.ipynb
Labels: size/M

#1436 small doc fixing
  bootcamp/tutorials/integration/build_rag_on_arm.md
  bootcamp/tutorials/quickstart/contextual_retrieval_with_milvus.ipynb
Labels: size/XS

#1437 Add ColPALI and HDBSCAN notebook
  bootcamp/tutorials/quickstart/hdbscan_clustering_with_milvus.ipynb
  bootcamp/tutorials/quickstart/use_ColPALI_with_milvus.ipynb
  images/hdbscan_clustering_with_milvus.png
Labels: size/XL

#1438 siliconflow
  bootcamp/tutorials/integration/build_RAG_with_milvus_and_siliconflow.ipynb
Labels: size/XL

#1439 added rag_visualization using t-SNE
  bootcamp/tutorials/quickstart/rag_visualization.ipynb
Labels: size/XL

#1440 optimize vector visualization
  bootcamp/tutorials/quickstart/vector_visualization.ipynb
Labels: size/L

#1441 more LLM RAG notebooks
  bootcamp/tutorials/integration/build_RAG_with_milvus_and_fireworks.ipynb
  bootcamp/tutorials/integration/build_RAG_with_milvus_and_lepton.ipynb
  bootcamp/tutorials/quickstart/vector_visualization.ipynb
Labels: size/XXL

#1442 fix badges
  bootcamp/tutorials/quickstart/hdbscan_clustering_with_milvus.ipynb
  bootcamp/tutorials/quickstart/use_ColPALI_with_milvus.ipynb
Labels: size/M

#1443 Correct ColPali name.
  bootcamp/tutorials/quickstart/use_ColPali_with_milvus.ipynb
Labels: size/S

#1444 use image to represent colpali formula
  bootcamp/tutorials/quickstart/use_ColPali_with_milvus.ipynb
  images/colpali_formula.png
Labels: size/XS

#1446 movie_recommendation_with_milvus
  bootcamp/tutorials/quickstart/movie_recommendation_with_milvus.ipynb
Labels: size/L

#1447 rag_with_milvus_and_unstructured
  bootcamp/tutorials/integration/pdf_files/WhatisMilvus.pdf
  bootcamp/tutorials/integration/rag_with_milvus_and_unstructured.ipynb
Labels: size/L

#1449 movie recommendation done
  bootcamp/tutorials/quickstart/movie_recommendation_with_milvus.ipynb
Labels: size/XXL

#1450 movie recommendation updated with better insertion logic
  bootcamp/tutorials/quickstart/movie_recommendation_with_milvus.ipynb
Labels: size/L

#1451 RAG_with_pii_and_milvus.md
  bootcamp/tutorials/integration/RAG_with_pii_and_milvus.md
Labels: size/L
