Repository milvus-io/bootcamp, pull requests merged in 2024-07, with the labels that each got.

#1366 refine rag description
  bootcamp/RAG/advanced_rag/vanilla_rag_with_langchain.ipynb
  bootcamp/tutorials/integration/evaluation_with_ragas.ipynb
  bootcamp/tutorials/integration/rag_with_milvus_and_haystack.ipynb
  bootcamp/tutorials/integration/rag_with_milvus_and_langchain.ipynb
  bootcamp/tutorials/integration/rag_with_milvus_and_llamaindex.ipynb
  bootcamp/tutorials/quickstart/build_RAG_with_milvus.ipynb
Labels: size/S

#1367 Update basic RAG chunking and eval notebook
  bootcamp/workshops/dbta_may_2024/1. RAG_basic.ipynb
Labels: size/XXL

#1369 Update basic RAG chunking and eval notebook
  bootcamp/workshops/dbta_may_2024/1. RAG_basic.ipynb
Labels: size/XXL

#1370 refine haystack
  bootcamp/tutorials/integration/rag_with_milvus_and_haystack.ipynb
Labels: size/S

#1371 Create README.md
  bootcamp/tutorials/quickstart/apps/README.md
Labels: size/XS

#1372 Change example data in milvus rag tutorial
  bootcamp/tutorials/quickstart/build_RAG_with_milvus.ipynb
Labels: size/L

#1374 Clean up notebooks for blog chunking eval
  bootcamp/Evaluation/data/blog_eval_answers.csv
  bootcamp/Evaluation/data/ground_truth_answers.csv
  bootcamp/Evaluation/eval_ragas.py
  bootcamp/Evaluation/eval_try2.ipynb
  bootcamp/workshops/dbta_may_2024/2. RAG_basic_eval_langchain.ipynb
  bootcamp/workshops/dbta_may_2024/3. RAG_advanced.ipynb
Labels: size/XXL

#1375 Rag demo
  bootcamp/tutorials/quickstart/apps/rag_search_with_milvus/.env
  bootcamp/tutorials/quickstart/apps/rag_search_with_milvus/README.md
  bootcamp/tutorials/quickstart/apps/rag_search_with_milvus/app.py
  bootcamp/tutorials/quickstart/apps/rag_search_with_milvus/ask_llm.py
  bootcamp/tutorials/quickstart/apps/rag_search_with_milvus/encoder.py
  bootcamp/tutorials/quickstart/apps/rag_search_with_milvus/insert.py
  bootcamp/tutorials/quickstart/apps/rag_search_with_milvus/milvus_utils.py
  bootcamp/tutorials/quickstart/apps/rag_search_with_milvus/pics/Milvus_Logo_Official.png
  bootcamp/tutorials/quickstart/apps/rag_search_with_milvus/pics/step1.png
  bootcamp/tutorials/quickstart/apps/rag_search_with_milvus/pics/step2.png
  bootcamp/tutorials/quickstart/apps/rag_search_with_milvus/pics/step3.png
  bootcamp/tutorials/quickstart/apps/rag_search_with_milvus/requirements.txt
Labels: size/L

#1376 Image demo
  bootcamp/tutorials/quickstart/apps/image_search_with_milvus/.env
  bootcamp/tutorials/quickstart/apps/image_search_with_milvus/README.md
  bootcamp/tutorials/quickstart/apps/image_search_with_milvus/app.py
  bootcamp/tutorials/quickstart/apps/image_search_with_milvus/encoder.py
  bootcamp/tutorials/quickstart/apps/image_search_with_milvus/insert.py
  bootcamp/tutorials/quickstart/apps/image_search_with_milvus/milvus_utils.py
  bootcamp/tutorials/quickstart/apps/image_search_with_milvus/pics/Milvus_Logo_Official.png
  bootcamp/tutorials/quickstart/apps/image_search_with_milvus/pics/step1.png
  bootcamp/tutorials/quickstart/apps/image_search_with_milvus/pics/step2_and_3.jpg
  bootcamp/tutorials/quickstart/apps/image_search_with_milvus/pics/step4.jpg
  bootcamp/tutorials/quickstart/apps/image_search_with_milvus/requirements.txt
Labels: size/L

#1377 Update README
  bootcamp/tutorials/quickstart/apps/rag_search_with_milvus/README.md
Labels: size/S

#1378 Add demo links in notebooks
  bootcamp/tutorials/quickstart/apps/image_search_with_milvus/README.md
  bootcamp/tutorials/quickstart/apps/image_search_with_milvus/pics/image_search_demo.png
  bootcamp/tutorials/quickstart/apps/rag_search_with_milvus/README.md
  bootcamp/tutorials/quickstart/apps/rag_search_with_milvus/pics/rag_demo.png
  bootcamp/tutorials/quickstart/build_RAG_with_milvus.ipynb
  bootcamp/tutorials/quickstart/image_search_with_milvus.ipynb
Labels: size/M

#1380 Fix typo
  bootcamp/tutorials/quickstart/build_RAG_with_milvus.ipynb
Labels: size/XS

#1381 Add app of multimodal_rag_with_milvus.
  bootcamp/tutorials/quickstart/apps/multimodal_rag_with_milvus/.env
  bootcamp/tutorials/quickstart/apps/multimodal_rag_with_milvus/.streamlit/config.toml
  bootcamp/tutorials/quickstart/apps/multimodal_rag_with_milvus/README.md
  bootcamp/tutorials/quickstart/apps/multimodal_rag_with_milvus/categories.txt
  bootcamp/tutorials/quickstart/apps/multimodal_rag_with_milvus/cfg.py
  bootcamp/tutorials/quickstart/apps/multimodal_rag_with_milvus/download_images.py
  bootcamp/tutorials/quickstart/apps/multimodal_rag_with_milvus/index.py
  bootcamp/tutorials/quickstart/apps/multimodal_rag_with_milvus/magiclens/data_utils.py
  bootcamp/tutorials/quickstart/apps/multimodal_rag_with_milvus/magiclens/inference.py
  bootcamp/tutorials/quickstart/apps/multimodal_rag_with_milvus/magiclens/layers.py
  bootcamp/tutorials/quickstart/apps/multimodal_rag_with_milvus/magiclens/model.py
  bootcamp/tutorials/quickstart/apps/multimodal_rag_with_milvus/pics/cir_demo.jpg
  bootcamp/tutorials/quickstart/apps/multimodal_rag_with_milvus/pics/milvus_logo.png
  bootcamp/tutorials/quickstart/apps/multimodal_rag_with_milvus/pics/step1.jpg
  bootcamp/tutorials/quickstart/apps/multimodal_rag_with_milvus/pics/step2.jpg
  bootcamp/tutorials/quickstart/apps/multimodal_rag_with_milvus/pics/step3.jpg
  bootcamp/tutorials/quickstart/apps/multimodal_rag_with_milvus/requirements.txt
  bootcamp/tutorials/quickstart/apps/multimodal_rag_with_milvus/reranker.py
  bootcamp/tutorials/quickstart/apps/multimodal_rag_with_milvus/retrieve.py
  bootcamp/tutorials/quickstart/apps/multimodal_rag_with_milvus/ui.py
Labels: size/XXL

#1383 Add demo of hybrid retrieval.
  bootcamp/tutorials/quickstart/apps/hybrid_demo_with_milvus/.streamlit/config.toml
  bootcamp/tutorials/quickstart/apps/hybrid_demo_with_milvus/README.md
  bootcamp/tutorials/quickstart/apps/hybrid_demo_with_milvus/index.py
  bootcamp/tutorials/quickstart/apps/hybrid_demo_with_milvus/pics/Milvus_Logo_Official.png
  bootcamp/tutorials/quickstart/apps/hybrid_demo_with_milvus/pics/demo.jpg
  bootcamp/tutorials/quickstart/apps/hybrid_demo_with_milvus/requirements.txt
  bootcamp/tutorials/quickstart/apps/hybrid_demo_with_milvus/ui.py
  bootcamp/tutorials/quickstart/apps/image_search_with_milvus/.streamlit/config.toml
  bootcamp/tutorials/quickstart/apps/rag_search_with_milvus/.streamlit/config.toml
Labels: size/L

#1384 Add demo for cir search.
  bootcamp/tutorials/quickstart/apps/cir_with_milvus/.env
  bootcamp/tutorials/quickstart/apps/cir_with_milvus/.streamlit/config.toml
  bootcamp/tutorials/quickstart/apps/cir_with_milvus/README.md
  bootcamp/tutorials/quickstart/apps/cir_with_milvus/categories.txt
  bootcamp/tutorials/quickstart/apps/cir_with_milvus/cfg.py
  bootcamp/tutorials/quickstart/apps/cir_with_milvus/download_images.py
  bootcamp/tutorials/quickstart/apps/cir_with_milvus/index.py
  bootcamp/tutorials/quickstart/apps/cir_with_milvus/magiclens/data_utils.py
  bootcamp/tutorials/quickstart/apps/cir_with_milvus/magiclens/inference.py
  bootcamp/tutorials/quickstart/apps/cir_with_milvus/magiclens/layers.py
  bootcamp/tutorials/quickstart/apps/cir_with_milvus/magiclens/model.py
  bootcamp/tutorials/quickstart/apps/cir_with_milvus/pics/cir_demo.jpg
  bootcamp/tutorials/quickstart/apps/cir_with_milvus/pics/edit.jpg
  bootcamp/tutorials/quickstart/apps/cir_with_milvus/pics/milvus_logo.png
  bootcamp/tutorials/quickstart/apps/cir_with_milvus/requirements.txt
  bootcamp/tutorials/quickstart/apps/cir_with_milvus/retrieve.py
  bootcamp/tutorials/quickstart/apps/cir_with_milvus/ui.py
Labels: size/XXL

#1385 fixed typos and updated readme file
  bootcamp/tutorials/quickstart/apps/hybrid_demo_with_milvus/README.md
  bootcamp/tutorials/quickstart/apps/hybrid_demo_with_milvus/pics/demo.jpg
  bootcamp/tutorials/quickstart/apps/hybrid_demo_with_milvus/pics/demo.png
  bootcamp/tutorials/quickstart/apps/hybrid_demo_with_milvus/ui.py
Labels: size/S

#1390 Add integration tutorial for camel
  bootcamp/tutorials/integration/rag_with_milvus_and_camel.ipynb
Labels: size/XL

#1389 Added Hybrid Search Notebook
  bootcamp/tutorials/quickstart/hybrid_search_with_milvus.ipynb
Labels: size/XL

#1392 Fix hybrid search tutorial
  bootcamp/tutorials/quickstart/hybrid_search_with_milvus.ipynb
Labels: size/XL

#1393 Change index type for dense vector field
  bootcamp/tutorials/quickstart/hybrid_search_with_milvus.ipynb
Labels: size/XS

#1394 Fix colab link for hybrid search tutorial
  bootcamp/tutorials/quickstart/hybrid_search_with_milvus.ipynb
Labels: size/XS

#1395 Fix typo
  bootcamp/tutorials/quickstart/hybrid_search_with_milvus.ipynb
Labels: size/XS, lgtm

#1399 Add CIR notebook
  bootcamp/tutorials/quickstart/cir_with_milvus.ipynb
Labels: size/L

#1400 Add multimodal rag notebook
  bootcamp/tutorials/quickstart/cir_with_milvus.ipynb
  bootcamp/tutorials/quickstart/multimodal_rag_with_milvus.ipynb
Labels: size/XL

#1402 Update using Milvus Lite, Meta llama 3.1, openai gpt-4o-mini
  bootcamp/workshops/dbta_may_2024/1. RAG_basic.ipynb
Labels: size/XXL
