Repository milvus-io/bootcamp, pull requests merged in 2024-01, with the labels that each got.

#1235 Update README, Add Cheat Sheet
  bootcamp/BestPractices.md
  bootcamp/RAG/readthedocs_zilliz_langchain.ipynb
  bootcamp/README.md
  bootcamp/Retrieval/imdb_milvus_client.ipynb
Labels: size/L

#1236 Rename CheatSheet and add images for it
  bootcamp/MilvusCheatSheet.md
  images/milvus_zilliz_overview.png
  images/oss_zilliz_architecture.png
Labels: size/S

#1242 Update introduction and links
  bootcamp/RAG/zilliz_pipeline_rag.ipynb
Labels: size/XS

#1244 Add Spark Milvus integration demos
  bootcamp/spark_milvus_demo/milvus-demo1-sink.scala
  bootcamp/spark_milvus_demo/milvus-demo2-bulkinsert.scala
  bootcamp/spark_milvus_demo/zilliz-demo1-sink.scala
  bootcamp/spark_milvus_demo/zilliz-demo2-import.scala
Labels: size/L

#1245 Update cheatsheet, draft a rough OSS eval
  bootcamp/Evaluation/eval_try2.ipynb
Labels: size/XXL

#1246 Update cheatsheet, draft a rough OSS eval
  bootcamp/MilvusCheatSheet.md
Labels: size/S

#1247 Small tweaks to variable names and text
  bootcamp/RAG/readthedocs_zilliz_langchain.ipynb
Labels: size/L

#1243 Update MilvusCheatSheet.md
  bootcamp/MilvusCheatSheet.md
Labels: size/S

#1250 Add custom RAG workflow OpenAI Assistant
  bootcamp/OpenAIAssistants/custom_RAG_workflow.ipynb
Labels: size/XXL

#1251 Add custom RAG workflow OpenAI Assistant
  bootcamp/OpenAIAssistants/custom_RAG_workflow.ipynb
Labels: size/XXL

#1252 Add text embeddings tutorial
  bootcamp/text_embeddings_tutorial.ipynb
Labels: size/L

#1253 add project id and chunksize in pipeline rag notebook
  bootcamp/RAG/pipeline_utils.py
  bootcamp/RAG/zilliz_pipeline_rag.ipynb
  bootcamp/RAG/zilliz_pipeline_rag_advanced.ipynb
  images/zilliz_api_key_cluster_id.jpeg
Labels: size/L

#1255 Openai embedding milvus sementic seach
  bootcamp/Integration/docs/openai_blog.txt
  bootcamp/Integration/openai_embedding.ipynb
  images/openai_embedding_scores.png
  images/openai_embedding_vector_size.png
Labels: size/XL
