Repository milvus-io/bootcamp, pull requests merged in 2024-06, with the labels that each got.

#1348 refine quickstart
  bootcamp/tutorials/quickstart/quickstart.ipynb
Labels: size/XL

#1350 Update connections notebook for Milvus Lite
  bootcamp/milvus_connect.ipynb
Labels: size/XXL

#1352 Update connections notebook for Milvus Lite
  bootcamp/milvus_connect.ipynb
Labels: size/XXL

#1354 Add connect notebook for Milvus Lite
  bootcamp/milvus_connect.ipynb
Labels: size/XXL

#1356 refine colab descriptions
  bootcamp/tutorials/integration/evaluation_with_ragas.ipynb
  bootcamp/tutorials/integration/memgpt_with_milvus.md
  bootcamp/tutorials/integration/milvus_and_DSPy.ipynb
  bootcamp/tutorials/integration/milvus_with_Jina.ipynb
  bootcamp/tutorials/integration/qa_with_milvus_and_hf.ipynb
  bootcamp/tutorials/integration/rag_with_milvus_and_bentoml.ipynb
  bootcamp/tutorials/integration/rag_with_milvus_and_haystack.ipynb
  bootcamp/tutorials/integration/rag_with_milvus_and_langchain.ipynb
  bootcamp/tutorials/integration/rag_with_milvus_and_llamaindex.ipynb
  bootcamp/tutorials/integration/semantic_search_with_milvus_and_openai.ipynb
  bootcamp/tutorials/integration/semantic_search_with_milvus_and_voyageai.ipynb
  bootcamp/tutorials/quickstart/build_RAG_with_milvus.ipynb
  bootcamp/tutorials/quickstart/image_search_with_milvus.ipynb
  bootcamp/tutorials/quickstart/quickstart.ipynb
Labels: size/S

#1357 Add connect notebook for Milvus Lite
  bootcamp/milvus_connect.ipynb
Labels: size/L

#1360 add drop old collection to makesure rerun normailly
  bootcamp/tutorials/integration/milvus_with_Jina.ipynb
  bootcamp/tutorials/integration/qa_with_milvus_and_hf.ipynb
  bootcamp/tutorials/integration/rag_with_milvus_and_bentoml.ipynb
  bootcamp/tutorials/integration/semantic_search_with_milvus_and_openai.ipynb
  bootcamp/tutorials/integration/semantic_search_with_milvus_and_voyageai.ipynb
  bootcamp/tutorials/quickstart/image_search_with_milvus.ipynb
  bootcamp/tutorials/quickstart/quickstart.ipynb
Labels: size/L

#1358 [Langchain] Add Advanced RAG with LangGraph
  bootcamp/RAG/advanced_rag/imgs/RAG_Agent_langGraph.png
  bootcamp/RAG/advanced_rag/langgraph-rag-agent-local.ipynb
Labels: size/XXL

#1361 Fastgpt
  bootcamp/tutorials/integration/fastgpt_with_milvus.md
Labels: size/M

#1362 vanna
  bootcamp/tutorials/integration/vanna_write_sql.ipynb
Labels: size/XL

#1364 add zilliz cloud description, add metadata filtering in LC & LI integration
  bootcamp/tutorials/integration/evaluation_with_ragas.ipynb
  bootcamp/tutorials/integration/milvus_and_DSPy.ipynb
  bootcamp/tutorials/integration/milvus_with_Jina.ipynb
  bootcamp/tutorials/integration/qa_with_milvus_and_hf.ipynb
  bootcamp/tutorials/integration/rag_with_milvus_and_bentoml.ipynb
  bootcamp/tutorials/integration/rag_with_milvus_and_haystack.ipynb
  bootcamp/tutorials/integration/rag_with_milvus_and_langchain.ipynb
  bootcamp/tutorials/integration/rag_with_milvus_and_llamaindex.ipynb
  bootcamp/tutorials/integration/semantic_search_with_milvus_and_openai.ipynb
  bootcamp/tutorials/integration/semantic_search_with_milvus_and_voyageai.ipynb
  bootcamp/tutorials/integration/vanna_write_sql.ipynb
  bootcamp/tutorials/quickstart/build_RAG_with_milvus.ipynb
  bootcamp/tutorials/quickstart/image_search_with_milvus.ipynb
Labels: size/XL

#1365 py38 description
  bootcamp/tutorials/integration/rag_with_milvus_and_bentoml.ipynb
  bootcamp/tutorials/quickstart/quickstart.ipynb
Labels: size/XS
