Repository milvus-io/bootcamp, pull requests merged in 2024-11, with the labels that each got.

#1452 Correct the dataset path used in contextual retrieval.
  bootcamp/tutorials/quickstart/contextual_retrieval_with_milvus.ipynb
Labels: size/M

#1453 use_milvus_in_private_gpt.md
  bootcamp/tutorials/integration/use_milvus_in_private_gpt.md
  images/private_gpt_ui.png
Labels: size/L

#1454 quickstart mem0 with milvus finished
  bootcamp/tutorials/integration/quickstart_mem0_with_milvus.ipynb
Labels: size/XL

#1448 Funnel Search and Matryoshkya Embeddings
  bootcamp/tutorials/milvus_usages/funnel-search.png
  bootcamp/tutorials/milvus_usages/funnel_search_with_matryoshka.ipynb
  bootcamp/tutorials/milvus_usages/results-ferris-buellers-day-off.png
  bootcamp/tutorials/milvus_usages/results-raiders-of-the-lost-ark.png
  bootcamp/tutorials/milvus_usages/results-the-shining.png
Labels: size/XL

#1456 Move Matroshkya tutorial into quickstart folder
  bootcamp/tutorials/quickstart/funnel-search.png
  bootcamp/tutorials/quickstart/funnel_search_with_matryoshka.ipynb
  bootcamp/tutorials/quickstart/results-ferris-buellers-day-off.png
  bootcamp/tutorials/quickstart/results-raiders-of-the-lost-ark.png
  bootcamp/tutorials/quickstart/results-the-shining.png
Labels: size/XS

#1455 fix badges
  bootcamp/tutorials/integration/quickstart_mem0_with_milvus.ipynb
Labels: size/XS

#1457 refine privategpt notebook
  bootcamp/tutorials/integration/use_milvus_in_private_gpt.md
Labels: size/S

#1458 knowlegde_table_with_milvus
  bootcamp/tutorials/integration/knowlegde_table_with_milvus.md
  images/knowlege_table.png
Labels: size/M

#1460 movie recommendation updated with newer comments and deletion of load()
  bootcamp/tutorials/quickstart/movie_recommendation_with_milvus.ipynb
Labels: size/L

#1461 use_milvus_in_docsgpt
  bootcamp/tutorials/integration/use_milvus_in_docsgpt.md
  images/doscgpt_ui.png
Labels: size/M

#1462 use_milvus_with_sambanova
  bootcamp/tutorials/integration/use_milvus_with_sambanova.md
  images/sambanava_ui.png
Labels: size/M

#1463 Milvus RAG with Dynamiq
  bootcamp/tutorials/integration/milvus_rag_with_dynamiq.ipynb
Labels: size/XL

#1464 build_RAG_with_milvus_and_gemini
  bootcamp/tutorials/integration/build_RAG_with_milvus_and_gemini.ipynb
Labels: size/XL

#1466 Little fixes to Image Search App
  .gitignore
  bootcamp/tutorials/quickstart/apps/image_search_with_milvus/README.md
  bootcamp/tutorials/quickstart/apps/image_search_with_milvus/app.py
Labels: size/XS

#1468 Cast MODEL_DIM to Integer
  bootcamp/tutorials/quickstart/apps/image_search_with_milvus/insert.py
Labels: size/XS

#1469 build rag with milvus and ollama tutorial
  bootcamp/tutorials/integration/build_RAG_with_milvus_and_ollama.ipynb
Labels: size/XL
