Repository milvus-io/bootcamp, pull requests merged in 2025-04, with the labels that each got.

#1520 updated feast with direct downloading from feast repo
  bootcamp/tutorials/integration/build_RAG_with_milvus_and_feast.ipynb
Labels: size/L

#1522 update .gitignore to include .env
  .gitignore
Labels: size/XS

#1523 add badge to the notebook
  bootcamp/tutorials/integration/mistral_ocr_with_milvus.ipynb
Labels: size/XS

#1521 Add text-to-image search notebook
  bootcamp/tutorials/quickstart/text_image_search_with_milvus.ipynb
Labels: size/L

#1516 Add tutorial: Full-Text Search by LlamaIndex and Milvus
  bootcamp/tutorials/integration/llamaindex/llamaindex_milvus_full_text_search.ipynb
  bootcamp/tutorials/integration/llamaindex/rag_with_milvus_and_llamaindex.ipynb
Labels: size/L

#1524 add haystack
  bootcamp/tutorials/integration/haystack/full_text_search_with_milvus_and_haystack.ipynb
  bootcamp/tutorials/integration/haystack/rag_with_milvus_and_haystack.ipynb
  bootcamp/tutorials/integration/langchain/full_text_search_with_langchain.ipynb
Labels: size/XL

#1526 rag with docling
  bootcamp/tutorials/integration/build_RAG_with_milvus_and_docling.ipynb
Labels: size/XL

#1528 aimon integration
  bootcamp/tutorials/integration/AIMon_milvus_integration.ipynb
Labels: size/XXL

#1530 refined rag with unstructured and milvus
  bootcamp/tutorials/integration/rag_with_milvus_and_unstructured.ipynb
Labels: size/L

#1529 updated the ragas integration notebook
  bootcamp/tutorials/integration/evaluation_with_ragas.ipynb
Labels: size/L

#1527 Add LlamaIndex Hybrid Search Notebook
  bootcamp/tutorials/integration/llamaindex/llamaindex_milvus_hybrid_search.ipynb
Labels: size/XL

#1531 Add notebook for LlamaIndex- Milvus metadata filtering
  bootcamp/tutorials/integration/llamaindex/llamaindex_milvus_metadata_filter.ipynb
Labels: size/L

#1532 remove discord link
  bootcamp/tutorials/integration/AIMon_milvus_integration.ipynb
Labels: size/XS

#1533 refactor full text search tutorial
  bootcamp/tutorials/quickstart/full_text_search_with_milvus.ipynb
Labels: size/XL
