Repository milvus-io/bootcamp, pull requests merged in 2025-02, with the labels that each got.

#1492 tutorial 1: s3+langchain+milvus; tutorial 2: s3+vectorETL+milvus
  bootcamp/tutorials/integration/ETL_using_vectorETL.ipynb
  bootcamp/tutorials/quickstart/build_RAG_from_s3_with_milvus.ipynb
Labels: size/XL

#1493 fix execution count for vectorETL and s3 to milvus tutorials
  bootcamp/tutorials/integration/ETL_using_vectorETL.ipynb
  bootcamp/tutorials/quickstart/build_RAG_from_s3_with_milvus.ipynb
Labels: size/XXL

#1495 remove the zilliz class usage display in langchain
  bootcamp/tutorials/integration/langchain/rag_with_milvus_and_langchain.ipynb
Labels: size/XS

#1496 move s3 notebook directory
  bootcamp/tutorials/integration/build_RAG_from_s3_with_milvus.ipynb
Labels: size/L

#1497 Fix Colab link and clean up a bit
  bootcamp/RAG/advanced_rag/langgraph-graphrag-agent-local.ipynb
Labels: size/L
