Repository milvus-io/bootcamp, pull requests merged in 2025-07, with the labels that each got.

#1558 add graph rag triplet extraction
  bootcamp/RAG/advanced_rag/rag_utils/graph_rag.py
  tutorials/quickstart/graph_rag_with_milvus.ipynb
Labels: size/L

#1559 add badge
  integration/langchain/langchain_milvus_async.ipynb
Labels: size/S

#1560 Update multimodal_rag_with_milvus.ipynb
  tutorials/quickstart/multimodal_rag_with_milvus.ipynb
Labels: size/XS
