Repository milvus-io/bootcamp, pull requests merged in 2025-03, with the labels that each got.

#1499 disclaimer of pipeline and refinement
  bootcamp/RAG/pipeline_utils.py
  bootcamp/RAG/zilliz_pipeline_rag.ipynb
  bootcamp/RAG/zilliz_pipeline_rag_advanced.ipynb
  bootcamp/RAG/zilliz_pipeline_rag_text.ipynb
  bootcamp/tutorials/integration/build_RAG_from_s3_with_milvus.ipynb
  bootcamp/tutorials/quickstart/apps/hybrid_demo_with_milvus/index.py
Labels: size/M

#1500 llamaindex milvus async
  bootcamp/tutorials/integration/llamaindex/llamaindex_milvus_async.ipynb
Labels: size/XL

#1501 llamastack document
  bootcamp/tutorials/integration/llama_stack_with_milvus.md
  bootcamp/tutorials/integration/llamaindex/rag_with_milvus_and_llamaindex.ipynb
Labels: size/L

#1502 add links of online demos
  bootcamp/tutorials/quickstart/hybrid_search_with_milvus.ipynb
  bootcamp/tutorials/quickstart/multimodal_rag_with_milvus.ipynb
Labels: size/XS

#1503 refactor the phidata to agno
  bootcamp/tutorials/integration/integrate_with_phidata.ipynb
Labels: size/M

#1504 fix the phidata(agno) show issue
  bootcamp/tutorials/integration/integrate_with_phidata.ipynb
Labels: size/XS

#1507 mindsdb integration
  bootcamp/tutorials/integration/integration_with_mindsdb.md
Labels: size/L

#1505 Add openai agent
  bootcamp/tutorials/integration/openai_agents_milvus.ipynb
Labels: size/L

#1508 refine openai_agents_milvus.ipynb
  bootcamp/tutorials/integration/openai_agents_milvus.ipynb
Labels: size/M

#1510 Add Mistral AI OCR with Milvus
  bootcamp/tutorials/integration/mistral_ocr_with_milvus.ipynb
Labels: size/XL

#1511 add an openai-agent image
  bootcamp/tutorials/integration/openai_agents_milvus.ipynb
  images/openai-agent.png
Labels: size/XS

#1514 update openai-agent image
  images/openai-agent.png
Labels: size/XS

#1515 Update langchain tutorials
  bootcamp/tutorials/integration/langchain/full_text_search_with_langchain.ipynb
  bootcamp/tutorials/integration/langchain/milvus_hybrid_search_retriever.ipynb
Labels: size/XS

#1519 build RAG with milvus and feast
  bootcamp/tutorials/integration/build_RAG_with_milvus_and_feast.ipynb
Labels: size/XL
