Repository milvus-io/bootcamp, pull requests merged in 2025-05, with the labels that each got.

#1534 tutorial: use milvus in anythingllm and build RAG with milvus and embed_anything
  bootcamp/tutorials/integration/build_RAG_with_milvus_and_embedAnything.ipynb
  bootcamp/tutorials/integration/use_milvus_in_anythingllm.md
  images/anythingllm_chat.png
  images/anythingllm_config.png
  images/anythingllm_dashboard.png
  images/anythingllm_milvus.png
  images/anythingllm_move_to_workspace.png
  images/anythingllm_save_and_embed.png
  images/anythingllm_upload_file.png
  images/anythingllm_upload_interface.png
  images/anythingllm_vectordb.png
  images/anythingllm_zilliz_cloud.png
Labels: size/L

#1536 Update .gitignore
  .gitignore
Labels: size/XS, lgtm

#1494 fix: correct typo "Lanage" to "Language" in tutorials/quickstart/build_RAG_with_milvus.ipynb
  bootcamp/tutorials/quickstart/build_RAG_with_milvus.ipynb
Labels: size/XS

#1537 Update .gitattributes
  .gitattributes
Labels: size/XS

#1538 Update use_ColPali_with_milvus.ipynb
  bootcamp/tutorials/quickstart/use_ColPali_with_milvus.ipynb
Labels: size/XS

#1539 Add dependencies for Funnel Search with Matryoshka
  bootcamp/tutorials/quickstart/funnel_search_with_matryoshka.ipynb
Labels: size/M

#1540 added n8n integration doc
  bootcamp/tutorials/integration/milvus_and_n8n.md
Labels: size/M

#1541 Fix model import. Change from milvus_model to pymilvus.model
  bootcamp/tutorials/quickstart/hybrid_search_with_milvus.ipynb
Labels: size/XS

#1542 Hdbscan data download
  bootcamp/tutorials/quickstart/hdbscan_clustering_with_milvus.ipynb
Labels: size/M

#1543 change drop_old from true to false
  bootcamp/tutorials/integration/build_RAG_from_s3_with_milvus.ipynb
  bootcamp/tutorials/integration/haystack/full_text_search_with_milvus_and_haystack.ipynb
  bootcamp/tutorials/integration/haystack/rag_with_milvus_and_haystack.ipynb
  bootcamp/tutorials/integration/langchain/basic_usage_langchain.ipynb
  bootcamp/tutorials/integration/langchain/full_text_search_with_langchain.ipynb
  bootcamp/tutorials/integration/langchain/milvus_hybrid_search_retriever.ipynb
  bootcamp/tutorials/integration/langchain/rag_with_milvus_and_langchain.ipynb
Labels: size/M

#1545 update milvus and n8n tutorial
  bootcamp/tutorials/integration/milvus_and_n8n.md
Labels: size/XS

#1552 optimize the dify_with_milvus.md
  integration/dify_with_milvus.md
Labels: size/M
