Repository milvus-io/bootcamp, pull requests merged in 2025-01, with the labels that each got.

#1480 build RAG with milvus and deepseek
  bootcamp/tutorials/integration/build_RAG_with_milvus_and_deepseek.ipynb
Labels: size/XL

#1481 attu tutorial
  bootcamp/tutorials/quickstart/quickstart_with_attu.md
  images/attu_after_data_insertion_1.png
  images/attu_after_data_insertion_2.png
  images/attu_expanded_searched_graph.png
  images/attu_login_page.png
  images/attu_searched_graph.png
  images/attu_searched_table.png
Labels: size/L

#1482 attu tutorial: updated with connect to milvus standalone
  bootcamp/tutorials/quickstart/quickstart_with_attu.md
Labels: size/S

#1483 refine quickstart_with_attu
  bootcamp/tutorials/quickstart/quickstart_with_attu.md
Labels: size/S

#1485 integrate_with_phidata
  bootcamp/tutorials/integration/integrate_with_phidata.ipynb
Labels: size/L

#1484 full_text_search_with_langchain
  bootcamp/tutorials/integration/langchain/full_text_search_with_langchain.ipynb
Labels: size/XL

#1487 move rag_with_milvus_and_langchain to the directory of langchain
  bootcamp/tutorials/integration/langchain/rag_with_milvus_and_langchain.ipynb
Labels: size/XS

#1488 1. build_RAG_with_milvus_and_firecrawl 2. build_RAG_with_milvus_and_crawl4ai
  bootcamp/tutorials/integration/build_RAG_with_milvus_and_crawl4ai.ipynb
  bootcamp/tutorials/integration/build_RAG_with_milvus_and_firecrawl.ipynb
Labels: size/XXL

#1489 Langchain doc
  bootcamp/tutorials/integration/langchain/basic_usage_langchain.ipynb
  bootcamp/tutorials/integration/langchain/milvus_hybrid_search_retriever.ipynb
Labels: size/XXL

#1490 fix build_RAG_with_milvus_and_crawl4ai execution count
  bootcamp/tutorials/integration/build_RAG_with_milvus_and_crawl4ai.ipynb
Labels: size/M

#1477 Multimodal retrieval with Amazon reviews dataset and LLVM reranking
  bootcamp/tutorials/quickstart/generation.png
  bootcamp/tutorials/quickstart/indexing.png
  bootcamp/tutorials/quickstart/multimodal_retrieval_amazon_reviews.ipynb
  bootcamp/tutorials/quickstart/retrieval.png
Labels: size/XL
